const glossaryBase = "/05-速查表/术语速查";

const pronunciations = new Map(Object.entries({
  token: "/ˈtoʊkən/",
  tokenizer: "/ˈtoʊkənaɪzər/",
  vocab: "/ˈvoʊkæb/",
  parameter: "/pəˈræmɪtər/",
  vector: "/ˈvɛktər/",
  matrix: "/ˈmeɪtrɪks/",
  embedding: "/ɪmˈbɛdɪŋ/",
  "hidden state": "/ˈhɪdən steɪt/",
  "hidden dimension": "/ˈhɪdən dɪˈmɛnʃən/",
  tensor: "/ˈtɛnsər/",
  "tensor shape": "/ˈtɛnsər ʃeɪp/",
  "representation space": "/ˌrɛprɪzɛnˈteɪʃən speɪs/",
  "high-dimensional space": "/ˌhaɪ dɪˈmɛnʃənəl speɪs/",
  "vector norm": "/ˈvɛktər nɔːrm/",
  "cosine similarity": "/ˈkoʊsaɪn ˌsɪməˈlærəti/",
  "Euclidean distance": "/juːˈklɪdiən ˈdɪstəns/",
  "linear projection": "/ˈlɪniər prəˈdʒɛkʃən/",
  subspace: "/ˈsʌbspeɪs/",
  "matrix rank": "/ˈmeɪtrɪks ræŋk/",
  "dimensionality reduction": "/dɪˌmɛnʃəˈnæləti rɪˈdʌkʃən/",
  PCA: "/ˌpiː siː ˈeɪ/",
  "t-SNE": "/ˌtiː ˈsniː/",
  UMAP: "/ˈjuːmæp/",
  logits: "/ˈlɑːdʒɪts/",
  softmax: "/ˈsɔːftmæks/",
  loss: "/lɔːs/",
  gradient: "/ˈɡreɪdiənt/",
  "gradient norm": "/ˈɡreɪdiənt nɔːrm/",
  "learning rate": "/ˈlɜːrnɪŋ reɪt/",
  optimizer: "/ˈɑːptəmaɪzər/",
  batch: "/bætʃ/",
  step: "/stɛp/",
  epoch: "/ˈɛpək/",
  context: "/ˈkɑːntɛkst/",
  Transformer: "/trænsˈfɔːrmər/",
  attention: "/əˈtɛnʃən/",
  "causal mask": "/ˈkɔːzəl mæsk/",
  backpropagation: "/ˌbækˌprɑːpəˈɡeɪʃən/",
  "cross-entropy": "/ˌkrɔːs ˈɛntrəpi/",
  checkpoint: "/ˈtʃɛkpɔɪnt/",
  pretraining: "/ˌpriːˈtreɪnɪŋ/",
  "continued pretraining": "/kənˈtɪnjuːd ˌpriːˈtreɪnɪŋ/",
  "post-training": "/ˌpoʊstˈtreɪnɪŋ/",
  "knowledge distillation": "/ˈnɑːlɪdʒ ˌdɪstəˈleɪʃən/",
  "teacher model": "/ˈtiːtʃər ˈmɑːdəl/",
  "student model": "/ˈstuːdənt ˈmɑːdəl/",
  "logit distillation": "/ˈlɑːdʒɪt ˌdɪstəˈleɪʃən/",
  "off-policy distillation": "/ˌɔːf ˈpɑːləsi ˌdɪstəˈleɪʃən/",
  "on-policy distillation": "/ˌɑːn ˈpɑːləsi ˌdɪstəˈleɪʃən/",
  "exposure bias": "/ɪkˈspoʊʒər ˈbaɪəs/",
  SFT: "/ˌɛs ɛf ˈtiː/",
  LoRA: "/ˈloʊrə/",
  QLoRA: "/ˌkjuː ˈloʊrə/",
  RLHF: "/ˌɑːr ɛl eɪtʃ ˈɛf/",
  DPO: "/ˌdiː piː ˈoʊ/",
  RAG: "/ræɡ/",
  Agent: "/ˈeɪdʒənt/",
  inference: "/ˈɪnfərəns/",
  "decoding strategy": "/diːˈkoʊdɪŋ ˈstrætədʒi/",
  overfitting: "/ˌoʊvərˈfɪtɪŋ/",
  "catastrophic forgetting": "/ˌkætəˈstrɑːfɪk fərˈɡɛtɪŋ/",
  "validation set": "/ˌvæləˈdeɪʃən sɛt/",
  baseline: "/ˈbeɪslaɪn/",
  "model hallucination": "/ˈmɑːdəl həˌluːsəˈneɪʃən/",
  factuality: "/ˌfæktʃuˈæləti/",
  faithfulness: "/ˈfeɪθfəlnəs/",
  "confidence calibration": "/ˈkɑːnfədəns ˌkæləˈbreɪʃən/",
  abstention: "/əbˈstɛnʃən/",
  quantization: "/ˌkwɑːntəˈzeɪʃən/",
  pruning: "/ˈpruːnɪŋ/",
  "KV Cache": "/ˌkeɪ viː ˈkæʃ/",
  "memory bandwidth": "/ˈmɛməri ˈbændwɪdθ/",
  "arithmetic intensity": "/ˌærɪθˈmɛtɪk ɪnˈtɛnsəti/",
  "Roofline model": "/ˈruːflaɪn ˈmɑːdəl/",
  "collective communication": "/kəˈlɛktɪv kəˌmjuːnəˈkeɪʃən/",
  AllReduce: "/ˌɔːl rɪˈduːs/",
  ZeRO: "/ˈzɪroʊ/",
  HBM: "/ˌeɪtʃ biː ˈɛm/",
  "inference latency": "/ˈɪnfərəns ˈleɪtənsi/",
  "inference throughput": "/ˈɪnfərəns ˈθruːpʊt/",
  "effective throughput": "/ɪˈfɛktɪv ˈθruːpʊt/",
  SLO: "/ˌɛs ɛl ˈoʊ/",
  TTFT: "/ˌtiː tiː ɛf ˈtiː/",
  TPOT: "/ˌtiː piː oʊ ˈtiː/",
  prefill: "/ˌpriːˈfɪl/",
  "chunked prefill": "/tʃʌŋkt ˌpriːˈfɪl/",
  "continuous batching": "/kənˈtɪnjuəs ˈbætʃɪŋ/",
  "paged KV cache": "/peɪdʒd ˌkeɪ viː ˈkæʃ/",
  "memory wall": "/ˈmɛməri wɔːl/",
  MoE: "/ˌɛm oʊ ˈiː/",
  "fixed-size state": "/ˌfɪkst saɪz ˈsteɪt/",
  "linear attention": "/ˈlɪniər əˈtɛnʃən/",
  "state-space model": "/ˈsteɪt speɪs ˈmɑːdəl/",
  "outer product": "/ˈaʊtər ˈprɑːdʌkt/",
  quantile: "/ˈkwɑːntaɪl/",
  softcap: "/ˈsɔːftkæp/",
  "total parameters": "/ˈtoʊtəl pəˈræmɪtərz/",
  "activated parameters": "/ˈæktəveɪtəd pəˈræmɪtərz/",
  "Scaling Laws": "/ˈskeɪlɪŋ lɔːz/",
  "expert parallelism": "/ˈɛkspɜːrt ˈpærəlɛlɪzəm/",
  "context parallelism": "/ˈkɑːntɛkst ˈpærəlɛlɪzəm/",
  "prefix cache": "/ˈpriːfɪks kæʃ/",
  "speculative decoding": "/ˈspɛkjələtɪv diːˈkoʊdɪŋ/",
  "test-time compute": "/ˈtɛst taɪm kəmˈpjuːt/",
  RLVR: "/ˌɑːr ɛl viː ˈɑːr/",
  "reward hacking": "/rɪˈwɔːrd ˈhækɪŋ/",
  "agent harness": "/ˈeɪdʒənt ˈhɑːrnəs/",
  QAT: "/ˌkjuː eɪ ˈtiː/",
  "native multimodal pretraining": "/ˈneɪtɪv ˌmʌltiˈmoʊdəl ˌpriːˈtreɪnɪŋ/",
  "multimodal alignment": "/ˌmʌltiˈmoʊdəl əˈlaɪnmənt/",
  KDA: "/ˌkeɪ diː ˈeɪ/",
  "Gated MLA": "/ˌɡeɪtəd ˌɛm ɛl ˈeɪ/",
  AttnRes: "/əˈtɛn rɛz/",
  "Stable LatentMoE": "/ˈsteɪbəl ˈleɪtənt ˌɛm oʊ ˈiː/",
  "Quantile Balancing": "/ˈkwɑːntaɪl ˈbælənsɪŋ/",
  MOPD: "/ˌɛm oʊ piː ˈdiː/"
}));

const speechOverrides = new Map(Object.entries({
  PCA: "P C A",
  "t-SNE": "T S N E",
  UMAP: "U map",
  SFT: "S F T",
  LoRA: "low rah",
  QLoRA: "Q low rah",
  RLHF: "R L H F",
  DPO: "D P O",
  RAG: "rag",
  "KV Cache": "K V cache",
  HBM: "H B M",
  TTFT: "T T F T",
  TPOT: "T P O T",
  MoE: "M O E",
  RLVR: "R L V R",
  QAT: "Q A T",
  KDA: "K D A",
  "Gated MLA": "gated M L A",
  AttnRes: "attention res",
  "Stable LatentMoE": "stable latent M O E",
  MOPD: "M O P D",
  SLO: "S L O",
  AllReduce: "all reduce",
  ZeRO: "zero"
}));

function defineTerm(term, anchor, aliases, summary, misconception, options = {}) {
  return {
    term,
    anchor: `term-${anchor}`,
    aliases,
    summary,
    misconception,
    pronunciation: options.pronunciation ?? pronunciations.get(term) ?? null,
    speech: options.speech ?? speechOverrides.get(term) ?? term,
    audio: options.audio ?? `/pronunciation/${anchor}.wav`,
    visual: options.visual ?? null,
    maxLinksPerPage: options.maxLinksPerPage ?? null,
    href: `${glossaryBase}#term-${anchor}`
  };
}

export const wikiTerms = [
  defineTerm("token", "token", ["token", "词元"], "文本经过分词规则得到的离散单元，随后会映射成整数 ID。", "token 必然等于一个字或一个完整单词。"),
  defineTerm("tokenizer", "tokenizer", ["tokenizer", "分词器"], "负责把文本切成 token，并在 token 与整数 ID 之间转换的规则和词表。", "tokenizer 是模型自己临时决定的切词方式。"),
  defineTerm("vocab", "vocab", ["vocab", "词表"], "tokenizer 可以表示的 token 集合；输出层通常也对这组 token 给出分数。", "词表包含了模型掌握的全部知识。"),
  defineTerm("parameter", "parameter", ["parameter", "parameters", "参数"], "模型中由训练确定的数字；训练时只有未冻结的参数会被更新。", "一个参数对应一条可直接读取的事实。"),
  defineTerm("vector", "vector", ["vector", "vectors", "向量"], "按顺序排列的一组数；维数是坐标数量，向量长度需要由这些数计算。", "向量有 10 个坐标，就表示它的长度等于 10。", {
    maxLinksPerPage: 2,
    visual: { type: "vector", values: [3, 4, 0, 0, 12], focus: 5, mathLabel: "a₅ = 12", codeLabel: "a[4] = 12", caption: "数学下标通常从 1 开始，Python 索引从 0 开始。" }
  }),
  defineTerm("matrix", "matrix", ["matrix", "matrices", "矩阵"], "按行列组织的一组数；在线性计算中，它可以充当把输入向量变成输出向量的规则。", "矩阵 W 就是输入空间或输出空间本身。", {
    maxLinksPerPage: 2,
    visual: { type: "pipeline", items: ["输入向量 x", "矩阵 W", "输出向量 y"], caption: "x 和 y 是空间中的具体点，W 是连接两个空间的变换规则。" }
  }),
  defineTerm("embedding", "embedding", ["embedding", "embeddings", "词嵌入", "嵌入"], "把离散 ID 映射为连续向量的可训练表示。", "embedding 是人工指定的固定语义坐标。", {
    visual: { type: "pipeline", items: ["token", "ID 42", "[0.2, -0.7, 1.1]"], caption: "同一内容依次换成离散单元、整数编号和连续向量。" }
  }),
  defineTerm("hidden state", "hidden-state", ["hidden state", "hidden states", "上下文化隐藏状态", "隐藏状态"], "某一层、某一位置结合当前上下文形成的向量表示。", "隐藏状态与静态 token Embedding 永远相同。"),
  defineTerm("hidden dimension", "hidden-dimension", ["hidden dimension", "hidden dimensions", "隐藏维度"], "每个位置的隐藏表示包含的坐标数量，常记为 D。", "每一维都有固定可命名的人类语义。"),
  defineTerm("tensor", "tensor", ["tensor", "tensors", "张量"], "按若干轴组织的一组数，是向量和矩阵的推广。", "张量各轴的含义可以不说明，只看总元素数。"),
  defineTerm("tensor shape", "tensor-shape", ["tensor shape", "tensor shapes", "张量形状"], "各轴长度组成的记录，例如 batch、time 和 hidden。", "相同数字排列代表相同轴含义。", {
    visual: { type: "pipeline", items: ["batch = 2", "time = 4", "hidden = 8"], caption: "形状 (2, 4, 8) 的三个数字必须连同轴名称一起读。" }
  }),
  defineTerm("representation space", "representation-space", ["representation space", "representation spaces", "表示空间"], "模型用一组坐标和方向组织隐藏表示的高维空间。", "每个坐标轴都是人工预先定义的概念。"),
  defineTerm("high-dimensional space", "high-dimensional-space", ["high-dimensional space", "high-dimensional spaces", "高维空间"], "需要许多坐标描述一个点或向量的空间。", "高维空间能像二维平面一样完整画出和直观看懂。"),
  defineTerm("vector norm", "vector-norm", ["vector norm", "vector norms", "向量范数"], "把向量总体幅度汇总成非负标量的规则。", "向量范数能说明向量具体朝哪个方向。", {
    visual: { type: "pipeline", items: ["[3, 4]", "3² + 4² = 25", "√25 = 5"], caption: "逐个平方、全部相加、最后开方。" }
  }),
  defineTerm("cosine similarity", "cosine-similarity", ["cosine similarity", "余弦相似度"], "用夹角比较两个非零向量方向是否接近。", "余弦相似度等同于欧氏距离或原始点积。"),
  defineTerm("Euclidean distance", "euclidean-distance", ["Euclidean distance", "欧氏距离"], "两个点之间直线距离对应的常用度量。", "欧氏距离在所有高维表示任务中都天然最合适。"),
  defineTerm("linear projection", "linear-projection", ["linear projection", "linear projections", "线性投影"], "用矩阵学习输入坐标的组合并映射到输出空间。", "线性投影只是 reshape，或输出维度越大知识越多。", {
    visual: { type: "pipeline", items: ["2 个输入坐标", "乘矩阵 W", "3 个输出坐标"], caption: "矩阵学习新的坐标组合，输出维数可以改变。" }
  }),
  defineTerm("subspace", "subspace", ["subspace", "subspaces", "子空间"], "高维空间中由较少独立方向张成的受限空间。", "子空间是从原向量机械切出的一段固定语义坐标。"),
  defineTerm("matrix rank", "matrix-rank", ["matrix rank", "矩阵秩", "低秩"], "矩阵可表达的独立方向数量。", "矩阵秩就是矩阵元素大小或参数数量。"),
  defineTerm("dimensionality reduction", "dimensionality-reduction", ["dimensionality reduction", "降维"], "把高维数据摘要到较少维度以分析、压缩或可视化。", "降维能无损保留高维空间的全部关系。"),
  defineTerm("PCA", "pca", ["PCA", "主成分分析"], "寻找保留较大线性变化方向的降维方法。", "前两个主成分代表全部结构或真实语义轴。"),
  defineTerm("t-SNE", "tsne", ["t-SNE", "tSNE"], "强调局部邻域可视分离的非线性降维方法。", "二维簇间距离和簇大小可直接作全局比较。"),
  defineTerm("UMAP", "umap", ["UMAP"], "基于邻域图和流形假设构造低维表示的方法。", "UMAP 输出图就是原高维空间的唯一真实地图。"),
  defineTerm("logits", "logits", ["logits", "logit"], "softmax 之前的任意实数分数，用来比较各候选 token。", "logits 已经是概率或正确率。"),
  defineTerm("softmax", "softmax", ["softmax"], "把一组分数转换为非负且总和为 1 的相对权重。", "softmax 会让模型答案自动真实或概率自动校准。", {
    visual: { type: "bars", items: [{ label: "候选 A", value: 27 }, { label: "候选 B", value: 73 }], caption: "logits [0, 1] 转成约 [0.27, 0.73]。" }
  }),
  defineTerm("loss", "loss", ["loss", "损失函数", "损失"], "训练目标对应的误差标量，优化器尝试让它下降。", "一个 loss 数值足以代表模型的全部质量。"),
  defineTerm("gradient", "gradient", ["gradient", "gradients", "梯度"], "loss 对各参数的局部变化率，指出当前附近怎样调整会改变 loss。", "梯度直接给出了全局最优答案。", {
    visual: { type: "pipeline", items: ["参数 5", "减去 0.1 × 2", "新参数 4.8"], caption: "梯度给局部方向，学习率控制迈多大一步。" }
  }),
  defineTerm("gradient norm", "gradient-norm", ["gradient norm", "gradient norms", "梯度范数"], "把一组参数梯度的总体幅度汇总成一个标量。", "梯度范数正常就表示每个参数的更新都合理。"),
  defineTerm("learning rate", "learning-rate", ["learning rate", "学习率"], "控制每次参数更新幅度的超参数。", "学习率越大，训练一定越快越好。"),
  defineTerm("optimizer", "optimizer", ["optimizer", "优化器"], "根据梯度及内部状态计算参数更新的算法，例如 AdamW。", "优化器负责计算前向预测或损失。"),
  defineTerm("batch", "batch", ["batch", "batches", "批次"], "一次前向与反向计算共同处理的一组样本。", "一个 batch 必然等于一次优化器更新或整个数据集。"),
  defineTerm("step", "step", ["step", "steps", "训练步"], "本课程默认指一次优化器更新；阅读日志时应先确认工具的定义。", "所有框架里的 step 都代表完全相同的事件。"),
  defineTerm("epoch", "epoch", ["epoch", "epochs", "轮次"], "训练过程大致遍历一遍训练集。", "一个 epoch 总有固定数量的 step。"),
  defineTerm("context", "context", ["context", "上下文"], "模型本次计算能够看到的 token 序列。", "放进上下文的信息已经永久写入模型参数。"),
  defineTerm("Transformer", "transformer", ["Transformer"], "由注意力、MLP、残差连接和归一化等模块组成的一类神经网络架构。", "所有大模型都只能采用同一种 Transformer 结构。"),
  defineTerm("attention", "attention", ["attention", "注意力机制", "注意力"], "根据 Query 与 Key 的匹配权重，对 Value 做加权汇总。", "注意力权重就是完整、可靠的人类可读解释。", {
    visual: { type: "pipeline", items: ["Q 与 K 匹配", "softmax 权重", "加权汇总 V"], caption: "先决定看多少，再把对应内容汇入当前位置。" }
  }),
  defineTerm("causal mask", "causal-mask", ["causal mask", "因果遮罩", "因果掩码"], "在自回归训练中阻止当前位置读取未来 token 的遮罩。", "它会阻止模型读取当前位置之前的内容。"),
  defineTerm("backpropagation", "backpropagation", ["backpropagation", "backprop", "反向传播"], "利用链式法则把输出误差逐层传回并计算梯度。", "反向传播本身就是优化器更新。"),
  defineTerm("cross-entropy", "cross-entropy", ["cross-entropy", "cross entropy", "交叉熵"], "衡量目标分布与预测分布差异的常用损失；分类时等价于正确类别的负对数概率。", "交叉熵就是准确率。"),
  defineTerm("checkpoint", "checkpoint", ["checkpoint", "checkpoints", "检查点"], "训练过程保存的权重及恢复训练所需状态快照。", "checkpoint 天然就是可直接上线的完整产品。"),
  defineTerm("pretraining", "pretraining", ["pretraining", "pre-training", "预训练"], "在大规模数据上学习通用模式的基础训练阶段。", "预训练数据越多，模型回答就必然越真实。"),
  defineTerm("continued pretraining", "continued-pretraining", ["continued pretraining", "continued-pretraining", "继续预训练"], "在已有基础模型上继续使用领域无标注数据训练，以适应新的语言分布。", "继续预训练等于用少量问答样本做 SFT。"),
  defineTerm("post-training", "post-training", ["post-training", "post training", "模型后训练", "后训练"], "在已有基座检查点上继续塑造指令遵循、偏好、推理、安全或拒答等行为的一组训练阶段。", "后训练会自动补齐事实知识，并保证所有原有能力不退化。"),
  defineTerm("knowledge distillation", "knowledge-distillation", ["knowledge distillation", "knowledge-distillation", "知识蒸馏", "模型蒸馏", "蒸馏"], "让学生模型学习教师模型提供的回答、概率、中间表示或策略信号。", "蒸馏会复制教师全部参数或保证能力无损。"),
  defineTerm("off-policy distillation", "off-policy-distillation", ["off-policy distillation", "离策略蒸馏"], "让学生在预先收集的教师轨迹或固定数据上学习，训练状态主要由教师或数据集决定。", "固定教师示范与学生推理时会访问的状态完全一致。"),
  defineTerm("on-policy distillation", "on-policy-distillation", ["on-policy distillation", "在策略蒸馏", "OPD"], "学生先生成自己会访问的前缀，再由教师在这些状态上提供逐 token 信号。", "教师更强或监督更密，就保证学生一定学得更好。"),
  defineTerm("exposure bias", "exposure-bias", ["exposure bias", "暴露偏差"], "训练时依赖理想历史，推理时却必须接着自己的输出生成，由此产生的状态分布差异。", "只要单步预测准确，误差就不会沿生成轨迹累积。"),
  defineTerm("teacher model", "teacher-model", ["teacher model", "teacher-model", "教师模型"], "在蒸馏中提供输出、概率、特征或评估信号的较强模型。", "教师模型产生的每个答案都是真值。"),
  defineTerm("student model", "student-model", ["student model", "student-model", "学生模型"], "在蒸馏中学习教师信号、通常更小或更便宜的模型。", "学生只能通过复制参数获得教师能力。"),
  defineTerm("logit distillation", "logit-distillation", ["logit distillation", "logit-distillation", "logit 蒸馏"], "让学生匹配教师在候选 token 上的 logits 或软概率分布。", "只要看最终答案就等于获得了教师的完整概率信息。"),
  defineTerm("SFT", "sft", ["SFT", "监督微调"], "用输入与理想输出示例进行监督训练，使模型更符合目标行为。", "SFT 会自动完成事实核验。"),
  defineTerm("LoRA", "lora", ["LoRA"], "冻结大部分基础权重，用低秩矩阵学习权重增量的参数高效微调方法。", "LoRA 会自动压缩推理模型或保证无损。"),
  defineTerm("QLoRA", "qlora", ["QLoRA"], "以低比特形式保存冻结的基础模型，同时训练 LoRA 适配器。", "LoRA 适配器本身被简单量化成 4 bit。"),
  defineTerm("RLHF", "rlhf", ["RLHF"], "利用人类偏好信号和强化学习优化模型行为的一类流程。", "所有对齐都只能通过 RLHF 完成。"),
  defineTerm("DPO", "dpo", ["DPO"], "直接利用偏好样本对优化策略，使偏好答案相对更可能。", "DPO 不包含任何偏好目标或参考约束。"),
  defineTerm("RAG", "rag", ["RAG", "检索增强生成"], "先检索外部资料，再把相关片段放进上下文辅助生成。", "检索到资料就能保证资料和答案都真实。"),
  defineTerm("Agent", "agent", ["Agent", "智能体"], "让模型参与工具选择、读取结果和多步决策循环的应用结构。", "Agent 可以脱离权限、预算和人工确认自主执行。"),
  defineTerm("inference", "inference", ["inference", "推理"], "使用训练好的参数，根据输入计算预测或生成结果。", "推理阶段通常会继续更新模型权重。"),
  defineTerm("decoding strategy", "decoding-strategy", ["decoding strategy", "解码策略", "token sampling", "token 采样"], "根据模型 logits 选择下一个 token 的规则，例如 greedy、temperature、top-k 或 top-p。", "解码策略负责产生模型没有学到的新知识，或随机性是幻觉的唯一原因。"),
  defineTerm("overfitting", "overfitting", ["overfitting", "过拟合"], "模型继续改善训练数据表现，却不能同步改善未见数据表现的现象。", "训练 loss 下降就一定没有过拟合。"),
  defineTerm("catastrophic forgetting", "catastrophic-forgetting", ["catastrophic forgetting", "灾难性遗忘"], "模型学习新任务或新分布后，原有能力显著退化的现象。", "只要新任务分数上升，就不需要检查旧能力。"),
  defineTerm("validation set", "validation-set", ["validation set", "validation data", "验证数据", "验证集"], "不参与梯度更新、用于选择配置和观察泛化表现的数据。", "反复针对验证集调参不会产生信息泄漏。"),
  defineTerm("baseline", "baseline", ["baseline", "model baseline", "模型基线"], "在采用更复杂方法前保存的可比较起点，例如规则、提示或未微调模型。", "基线只是临时演示，方法升级后就可以丢弃。", { maxLinksPerPage: 1 }),
  defineTerm("model hallucination", "model-hallucination", ["model hallucination", "模型幻觉"], "模型生成了流畅或自信、但与事实、给定证据或任务状态不一致的内容。", "模型幻觉只由随机采样造成，关闭 temperature 就能彻底解决。"),
  defineTerm("factuality", "factuality", ["factuality", "事实性"], "回答中的可核验主张与外部事实是否一致。", "事实正确就表示回答一定忠于当前给定证据。"),
  defineTerm("faithfulness", "faithfulness", ["faithfulness", "证据忠实度", "回答忠实度"], "回答中的主张是否得到当前给定证据或工具结果支持。", "忠于证据就能证明证据本身真实、最新且完整。"),
  defineTerm("confidence calibration", "confidence-calibration", ["confidence calibration", "置信度校准", "模型校准"], "让模型给出的置信程度与长期观察到的正确率更匹配。", "校准会把模型不知道的事实自动变成正确答案。"),
  defineTerm("abstention", "abstention", ["abstention", "selective prediction", "选择性回答", "模型拒答"], "当证据或置信不足时选择不作答，并在错误风险与覆盖率之间取舍。", "拒答越多就一定越可靠，或拒答能消除底层错误。"),
  defineTerm("quantization", "quantization", ["quantization", "量化"], "用更低精度表示权重或激活，以换取更低内存和更高效率。", "量化总能四倍加速且完全没有质量变化。"),
  defineTerm("pruning", "pruning", ["pruning", "structured pruning", "结构化剪枝", "剪枝"], "删除权重、通道、头或层等部分结构以降低模型规模或计算。", "出现很多零就一定能在目标硬件上变快。"),
  defineTerm("KV Cache", "kv-cache", ["KV Cache", "KV 缓存"], "自回归生成时缓存历史 token 的 Key/Value，避免每一步重复计算。", "KV Cache 主要用于降低训练显存。"),
  defineTerm("memory bandwidth", "memory-bandwidth", ["memory bandwidth", "显存带宽"], "单位时间内处理器与显存之间能够传输的数据量，常限制自回归解码等数据搬运密集任务。", "显存带宽与显存容量或标称计算峰值是同一个指标。"),
  defineTerm("arithmetic intensity", "arithmetic-intensity", ["arithmetic intensity", "算术强度"], "计算量与数据搬运量之比，用来判断任务更可能受计算峰值还是带宽限制。", "算术强度越高就代表模型质量或实际速度一定越高。"),
  defineTerm("Roofline model", "roofline-model", ["Roofline model", "Roofline 模型", "Roofline"], "把峰值计算能力与带宽乘算术强度两条上限放在同一性能图中的分析模型。", "它能脱离真实测量，直接给出唯一优化方案。"),
  defineTerm("collective communication", "collective-communication", ["collective communication", "集合通信"], "多设备共同参与的数据交换操作族，例如规约、聚合、广播和全互换。", "用了多卡后，通信成本会自动被计算完全隐藏。"),
  defineTerm("AllReduce", "allreduce", ["AllReduce", "all-reduce", "全规约"], "把各设备上的对应数据规约，并把完整结果返回每个参与设备。", "它只是把每张卡的数据集中到一张卡。"),
  defineTerm("ZeRO", "zero", ["ZeRO", "Zero Redundancy Optimizer"], "通过分片优化器状态、梯度和参数，减少数据并行训练中的重复显存占用。", "ZeRO 阶段越高就必然训练越快。"),
  defineTerm("HBM", "hbm", ["HBM", "High Bandwidth Memory", "高带宽内存"], "靠近加速器、为高吞吐数据访问设计的高带宽内存。", "HBM 容量越大就自动代表所有训练和推理都更快。"),
  defineTerm("inference latency", "inference-latency", ["inference latency", "推理延迟"], "一次推理请求从进入系统到产生所需结果所经历的时间，需要说明统计口径和负载。", "平均延迟足以代表首 token、每 token 和尾延迟体验。"),
  defineTerm("inference throughput", "inference-throughput", ["inference throughput", "推理吞吐", "token throughput", "token 吞吐"], "单位时间内系统完成的请求数或生成的 token 数，必须连同并发和负载说明。", "吞吐越高就代表每个用户等待越短。"),
  defineTerm("effective throughput", "effective-throughput", ["effective throughput", "goodput", "有效吞吐"], "只统计同时满足质量、延迟、错误率等服务约束的有效工作量。", "总 tokens/s 上升就必然代表有效吞吐上升。"),
  defineTerm("SLO", "slo", ["SLO", "service level objective", "服务等级目标"], "为指定负载和统计窗口设定的可度量服务目标，例如 TTFT、TPOT、错误率或可用性边界。", "只写“响应要快”就已经是可验证的 SLO。"),
  defineTerm("TTFT", "ttft", ["TTFT", "time to first token", "首 token 延迟"], "生成请求从进入系统到返回第一个输出 token 的时间。", "TTFT 能代表后续每个 token 的生成速度。"),
  defineTerm("TPOT", "tpot", ["TPOT", "time per output token", "每 token 延迟"], "首 token 之后，每生成一个输出 token 的平均时间口径。", "TPOT 包含全部排队、检索和首轮 prefill 时间。"),
  defineTerm("prefill", "prefill", ["prefill", "prompt prefill", "预填充阶段"], "推理时并行处理完整输入上下文、建立首轮隐藏状态和 KV Cache 的阶段。", "prefill 会一次性生成完整回答，或它与逐 token decode 是同一性能阶段。"),
  defineTerm("chunked prefill", "chunked-prefill", ["chunked prefill", "chunked-prefilling", "分块预填充"], "把长输入的 prefill 拆到多个调度步，使它能与正在 decode 的请求共享执行预算。", "切块只改变调度，不需要检查实现语义、延迟或吞吐权衡。"),
  defineTerm("continuous batching", "continuous-batching", ["continuous batching", "连续批处理"], "推理服务根据请求到达与完成动态调整 batch，使设备持续处理可运行请求。", "连续批处理必然同时降低单请求延迟并提高吞吐。"),
  defineTerm("paged KV cache", "paged-kv-cache", ["paged KV cache", "PagedAttention", "分页 KV Cache", "分页 KV 缓存"], "把 KV Cache 按固定块管理和映射，以降低碎片并支持动态请求。", "它会改变模型注意力语义、增加知识或自动减少每个 token 的缓存内容。"),
  defineTerm("memory wall", "memory-wall", ["memory wall", "内存墙"], "计算速度提升后，数据搬运速度成为整体性能主要限制的现象。", "内存墙只是显存容量不足，换更大容量就一定解决。"),
  defineTerm("MoE", "moe", ["MoE", "混合专家"], "通过路由让每个 token 只激活部分专家子网络的架构。", "多个完整模型对同一答案投票。"),
  defineTerm("fixed-size state", "fixed-size-state", ["fixed-size state", "固定状态", "固定形状状态"], "用固定数量的数值递推压缩历史，而不是为每个 token 保留一份独立缓存。", "固定大小等于能无损记住无限历史。"),
  defineTerm("linear attention", "linear-attention", ["linear attention", "线性注意力"], "把注意力改写为可递推或可重排的状态计算，使部分成本对序列长度近似线性。", "所有线性注意力都无损等价于 softmax 注意力。"),
  defineTerm("state-space model", "state-space-model", ["state-space model", "state space model", "SSM", "状态空间模型"], "用状态递推处理序列的一类模型，常以固定形状状态压缩历史。", "状态空间模型自动保留任意长度历史的全部细节。"),
  defineTerm("outer product", "outer-product", ["outer product", "外积"], "把两个向量组合成矩阵，常用于把键方向与值内容写入状态。", "外积与得到单个标量的点积相同。"),
  defineTerm("quantile", "quantile", ["quantile", "quantiles", "分位数"], "按排序位置描述数据分布阈值的统计量；具体插值口径需明确。", "分位数在所有软件和样本规模下只有一种计算定义。"),
  defineTerm("softcap", "softcap", ["softcap", "平滑封顶"], "用平滑函数限制数值幅度，同时保留连续梯度。", "封顶后就自动没有溢出、稳定性或质量问题。"),
  defineTerm("total parameters", "total-parameters", ["total parameters", "总参数量"], "模型包含的全部可训练参数规模，包括稀疏 MoE 中未被当前 token 选择的专家。", "等于每个 token 实际经过的参数量。"),
  defineTerm("activated parameters", "activated-parameters", ["activated parameters", "激活参数", "激活参数量"], "稀疏模型一次 token 计算实际经过的参数规模口径。", "可以直接当作精确 FLOPs 或完整显存占用。"),
  defineTerm("Scaling Laws", "scaling-laws", ["Scaling Laws", "scaling law", "scaling laws", "缩放定律"], "在限定数据、模型与计算范围内观察到的经验缩放关系。", "参数翻倍就保证能力按固定比例增长。"),
  defineTerm("expert parallelism", "expert-parallelism", ["expert parallelism", "专家并行"], "把 MoE 专家分布到不同设备，并按路由交换 token 的并行方式。", "只减少计算而不会引入通信或负载不均。"),
  defineTerm("context parallelism", "context-parallelism", ["context parallelism", "上下文并行"], "把同一长序列的不同片段分到多个设备协同计算。", "与把不同样本分给设备的数据并行相同。"),
  defineTerm("prefix cache", "prefix-cache", ["prefix cache", "prefix caching", "前缀缓存"], "复用多个请求完全相同前缀已经计算出的中间状态。", "文本大致相似或权限不同也能直接复用。"),
  defineTerm("speculative decoding", "speculative-decoding", ["speculative decoding", "推测解码"], "由草稿模型提出候选，再由目标模型批量验证的解码优化。", "草稿模型可以绕过目标模型直接决定输出分布。"),
  defineTerm("test-time compute", "test-time-compute", ["test-time compute", "test time compute", "测试时计算", "推理时计算"], "在推理阶段增加采样、搜索、验证或思考预算，以换取任务质量。", "增加推理预算就等于改变了模型训练参数。"),
  defineTerm("RLVR", "rlvr", ["RLVR", "reinforcement learning with verifiable rewards", "可验证奖励强化学习"], "使用程序或明确验证器产生奖励来训练策略的一类强化学习方法。", "验证器给出的高分必然等于真实任务完成。"),
  defineTerm("reward hacking", "reward-hacking", ["reward hacking", "奖励投机"], "策略利用奖励或验证器漏洞拿到高分，却没有完成真实目标。", "分数提高就一定代表任务能力提高。"),
  defineTerm("agent harness", "agent-harness", ["agent harness"], "包围模型的系统提示、工具、执行循环、上下文管理与错误恢复机制。", "排行榜中的 Agent 成绩只反映基础模型权重。"),
  defineTerm("QAT", "qat", ["QAT", "quantization-aware training", "量化感知训练"], "训练时模拟目标低精度数值效果，使参数提前适应部署格式。", "所有组件都必须使用同一种低比特格式且不会掉点。"),
  defineTerm("native multimodal pretraining", "native-multimodal-pretraining", ["native multimodal pretraining", "原生多模态预训练", "原生多模态"], "在基础预训练阶段共同学习文本与其他模态表示，而非只在语言模型完成后外挂对齐。", "只要训练得早就自动优于所有后接视觉方案。"),
  defineTerm("multimodal alignment", "multimodal-alignment", ["multimodal alignment", "模态对齐", "跨模态对齐"], "通过配对数据和训练目标，让不同模态的表示能够对应同一对象、事件或任务关系。", "张量维度能够连接就表示不同模态已经在语义上对齐。"),
  defineTerm("KDA", "kda", ["KDA", "Kimi Delta Attention"], "Kimi K3 使用的门控 delta 状态更新注意力，以固定形状状态压缩历史。", "固定状态能无损替代所有全局注意力层。"),
  defineTerm("Gated MLA", "gated-mla", ["Gated MLA", "门控 MLA"], "Kimi K3 中带门控的多头潜在注意力，用于保留 token 级全局交互。", "与 KDA 的固定状态读写完全相同。"),
  defineTerm("AttnRes", "attnres", ["AttnRes", "Attention Residuals", "注意力残差"], "让当前层按学习到的权重读取多个历史层或块表示的深度连接。", "普通残差相加换了一个名称。"),
  defineTerm("Stable LatentMoE", "stable-latent-moe", ["Stable LatentMoE", "LatentMoE"], "在较窄潜空间中进行稀疏专家计算，并加入尺度稳定与负载均衡设计。", "总参数、激活参数、通信和显存都按同一比例下降。"),
  defineTerm("Quantile Balancing", "quantile-balancing", ["Quantile Balancing", "QB", "分位数均衡"], "按专家路由分数的分位位置更新选择偏置的负载均衡方法。", "一次更新就保证此后每个专家永远获得相同负载。"),
  defineTerm("MOPD", "mopd", ["MOPD", "Mixture-of-Policies Distillation"], "把多个领域与推理努力策略的行为蒸馏回一个学生模型的后训练方法。", "多个教师总能被无损合并成一个模型。")
];

export const wikiAliases = wikiTerms.flatMap((term) =>
  term.aliases.map((alias) => ({ alias, term }))
);
