const glossaryBase = "/05-速查表/术语速查";

const pronunciations = new Map(Object.entries({
  token: "/ˈtoʊkən/",
  "token ID": "/ˈtoʊkən aɪ ˈdiː/",
  tokenizer: "/ˈtoʊkənaɪzər/",
  BPE: "/ˌbiː piː ˈiː/",
  vocab: "/ˈvoʊkæb/",
  parameter: "/pəˈræmɪtər/",
  "trainable parameters": "/ˈtreɪnəbəl pəˈræmɪtərz/",
  "language model": "/ˈlæŋɡwɪdʒ ˈmɑːdəl/",
  "large language model": "/ˌlɑːrdʒ ˈlæŋɡwɪdʒ ˈmɑːdəl/",
  "neural network": "/ˈnʊrəl ˈnɛtwɜːrk/",
  "model architecture": "/ˈmɑːdəl ˈɑːrkəˌtɛktʃər/",
  "model weights": "/ˈmɑːdəl weɪts/",
  "base model": "/beɪs ˈmɑːdəl/",
  "foundation model": "/faʊnˈdeɪʃən ˈmɑːdəl/",
  "training sample": "/ˈtreɪnɪŋ ˈsæmpəl/",
  dataset: "/ˈdeɪtəˌsɛt/",
  corpus: "/ˈkɔːrpəs/",
  "training label": "/ˈtreɪnɪŋ ˈleɪbəl/",
  "data annotation": "/ˈdeɪtə ˌænəˈteɪʃən/",
  "training objective": "/ˈtreɪnɪŋ əbˈdʒɛktɪv/",
  "supervision signal": "/ˌsuːpərˈvɪʒən ˈsɪɡnəl/",
  "self-supervised learning": "/ˌsɛlf ˈsuːpərvaɪzd ˈlɜːrnɪŋ/",
  "forward pass": "/ˈfɔːrwərd pæs/",
  activation: "/ˌæktəˈveɪʃən/",
  "decode phase": "/diːˈkoʊd feɪz/",
  "gradient descent": "/ˈɡreɪdiənt dɪˈsɛnt/",
  hyperparameter: "/ˈhaɪpər pəˌræmɪtər/",
  "random seed": "/ˈrændəm siːd/",
  "gradient accumulation": "/ˈɡreɪdiənt əˌkjuːmjəˈleɪʃən/",
  "mixed precision training": "/ˌmɪkst prɪˈsɪʒən ˈtreɪnɪŋ/",
  regularization: "/ˌrɛɡjələrəˈzeɪʃən/",
  "early stopping": "/ˈɜːrli ˈstɑːpɪŋ/",
  generalization: "/ˌdʒɛnərələˈzeɪʃən/",
  "data leakage": "/ˈdeɪtə ˈliːkɪdʒ/",
  "data contamination": "/ˈdeɪtə kənˌtæməˈneɪʃən/",
  vector: "/ˈvɛktər/",
  matrix: "/ˈmeɪtrɪks/",
  embedding: "/ɪmˈbɛdɪŋ/",
  "hidden state": "/ˈhɪdən steɪt/",
  "hidden dimension": "/ˈhɪdən dɪˈmɛnʃən/",
  tensor: "/ˈtɛnsər/",
  "tensor shape": "/ˈtɛnsər ʃeɪp/",
  "representation space": "/ˌrɛprɪzɛnˈteɪʃən speɪs/",
  "high-dimensional space": "/ˌhaɪ dɪˈmɛnʃənəl speɪs/",
  "vector norm": "/ˈvɛktər nɔːrm/",
  "cosine similarity": "/ˈkoʊsaɪn ˌsɪməˈlærəti/",
  "Euclidean distance": "/juːˈklɪdiən ˈdɪstəns/",
  "linear projection": "/ˈlɪniər prəˈdʒɛkʃən/",
  subspace: "/ˈsʌbspeɪs/",
  "matrix rank": "/ˈmeɪtrɪks ræŋk/",
  "low rank": "/ˌloʊ ˈræŋk/",
  "dimensionality reduction": "/dɪˌmɛnʃəˈnæləti rɪˈdʌkʃən/",
  PCA: "/ˌpiː siː ˈeɪ/",
  "t-SNE": "/ˌtiː ˈsniː/",
  UMAP: "/ˈjuːmæp/",
  logits: "/ˈlɑːdʒɪts/",
  softmax: "/ˈsɔːftmæks/",
  loss: "/lɔːs/",
  gradient: "/ˈɡreɪdiənt/",
  "gradient norm": "/ˈɡreɪdiənt nɔːrm/",
  "learning rate": "/ˈlɜːrnɪŋ reɪt/",
  optimizer: "/ˈɑːptəmaɪzər/",
  AdamW: "/ˈædəm ˈdʌbəljuː/",
  batch: "/bætʃ/",
  "batch size": "/bætʃ saɪz/",
  "effective batch size": "/ɪˈfɛktɪv bætʃ saɪz/",
  step: "/stɛp/",
  epoch: "/ˈɛpək/",
  context: "/ˈkɑːntɛkst/",
  Transformer: "/trænsˈfɔːrmər/",
  "Transformer Block": "/trænsˈfɔːrmər blɑːk/",
  attention: "/əˈtɛnʃən/",
  "self-attention": "/ˌsɛlf əˈtɛnʃən/",
  "positional mechanism": "/pəˈzɪʃənəl ˈmɛkəˌnɪzəm/",
  normalization: "/ˌnɔːrmələˈzeɪʃən/",
  "residual connection": "/rɪˈzɪdʒuəl kəˈnɛkʃən/",
  MLP: "/ˌɛm ɛl ˈpiː/",
  CNN: "/ˌsiː ɛn ˈɛn/",
  RNN: "/ˌɑːr ɛn ˈɛn/",
  LSTM: "/ˌɛl ɛs tiː ˈɛm/",
  GRU: "/ˌdʒiː ɑːr ˈjuː/",
  autoencoder: "/ˌɔːtoʊɪnˈkoʊdər/",
  GAN: "/ɡæn/",
  "diffusion model": "/dɪˈfjuːʒən ˈmɑːdəl/",
  GNN: "/ˌdʒiː ɛn ˈɛn/",
  "output head": "/ˈaʊtpʊt hɛd/",
  "causal mask": "/ˈkɔːzəl mæsk/",
  backpropagation: "/ˌbækˌprɑːpəˈɡeɪʃən/",
  "cross-entropy": "/ˌkrɔːs ˈɛntrəpi/",
  checkpoint: "/ˈtʃɛkpɔɪnt/",
  "fine-tuning": "/ˈfaɪn ˌtuːnɪŋ/",
  "full fine-tuning": "/ˈfʊl ˈfaɪn ˌtuːnɪŋ/",
  PEFT: "/ˌpiː iː ɛf ˈtiː/",
  adapter: "/əˈdæptər/",
  pretraining: "/ˌpriːˈtreɪnɪŋ/",
  "continued pretraining": "/kənˈtɪnjuːd ˌpriːˈtreɪnɪŋ/",
  "post-training": "/ˌpoʊstˈtreɪnɪŋ/",
  "knowledge distillation": "/ˈnɑːlɪdʒ ˌdɪstəˈleɪʃən/",
  "teacher model": "/ˈtiːtʃər ˈmɑːdəl/",
  "student model": "/ˈstuːdənt ˈmɑːdəl/",
  "logit distillation": "/ˈlɑːdʒɪt ˌdɪstəˈleɪʃən/",
  "off-policy distillation": "/ˌɔːf ˈpɑːləsi ˌdɪstəˈleɪʃən/",
  "on-policy distillation": "/ˌɑːn ˈpɑːləsi ˌdɪstəˈleɪʃən/",
  "exposure bias": "/ɪkˈspoʊʒər ˈbaɪəs/",
  SFT: "/ˌɛs ɛf ˈtiː/",
  LoRA: "/ˈloʊrə/",
  QLoRA: "/ˌkjuː ˈloʊrə/",
  RLHF: "/ˌɑːr ɛl eɪtʃ ˈɛf/",
  DPO: "/ˌdiː piː ˈoʊ/",
  "model alignment": "/ˈmɑːdəl əˈlaɪnmənt/",
  "preference data": "/ˈprɛfərəns ˈdeɪtə/",
  "preference optimization": "/ˈprɛfərəns ˌɑːptəməˈzeɪʃən/",
  "reward model": "/rɪˈwɔːrd ˈmɑːdəl/",
  "reinforcement learning": "/ˌriːɪnˈfɔːrsmənt ˈlɜːrnɪŋ/",
  "policy model": "/ˈpɑːləsi ˈmɑːdəl/",
  "advantage estimate": "/ədˈvæntɪdʒ ˈɛstəmət/",
  rollout: "/ˈroʊlˌaʊt/",
  verifier: "/ˈvɛrəˌfaɪər/",
  GRPO: "/ˌdʒiː ɑːr piː ˈoʊ/",
  "regression test set": "/rɪˈɡrɛʃən tɛst sɛt/",
  RAG: "/ræɡ/",
  Agent: "/ˈeɪdʒənt/",
  "Agent Swarm": "/ˈeɪdʒənt swɔːrm/",
  inference: "/ˈɪnfərəns/",
  reasoning: "/ˈriːzənɪŋ/",
  "reasoning effort": "/ˈriːzənɪŋ ˈɛfərt/",
  "thinking budget": "/ˈθɪŋkɪŋ ˈbʌdʒɪt/",
  "thinking level": "/ˈθɪŋkɪŋ ˈlɛvəl/",
  "adaptive thinking": "/əˈdæptɪv ˈθɪŋkɪŋ/",
  "model routing": "/ˈmɑːdəl ˈraʊtɪŋ/",
  "model fallback": "/ˈmɑːdəl ˈfɔːlbæk/",
  "context compaction": "/ˈkɑːntɛkst kəmˈpækʃən/",
  "capability regression": "/ˌkeɪpəˈbɪləti rɪˈɡrɛʃən/",
  "decoding strategy": "/diːˈkoʊdɪŋ ˈstrætədʒi/",
  "greedy decoding": "/ˈɡriːdi diːˈkoʊdɪŋ/",
  "top-k sampling": "/ˌtɑːp ˈkeɪ ˈsæmplɪŋ/",
  "top-p sampling": "/ˌtɑːp ˈpiː ˈsæmplɪŋ/",
  fitting: "/ˈfɪtɪŋ/",
  overfitting: "/ˌoʊvərˈfɪtɪŋ/",
  "catastrophic forgetting": "/ˌkætəˈstrɑːfɪk fərˈɡɛtɪŋ/",
  "validation set": "/ˌvæləˈdeɪʃən sɛt/",
  "training set": "/ˈtreɪnɪŋ sɛt/",
  "test set": "/ˈtɛst sɛt/",
  baseline: "/ˈbeɪslaɪn/",
  "model evaluation": "/ˈmɑːdəl ɪˌvæljuˈeɪʃən/",
  benchmark: "/ˈbɛntʃˌmɑːrk/",
  "ablation study": "/əˈbleɪʃən ˈstʌdi/",
  "ground truth": "/ˌɡraʊnd ˈtruːθ/",
  "model card": "/ˈmɑːdəl kɑːrd/",
  "data card": "/ˈdeɪtə kɑːrd/",
  "LLM-as-a-Judge": "/ˌɛl ɛl ɛm æz ə ˈdʒʌdʒ/",
  "pass@k": "/pæs æt keɪ/",
  "model hallucination": "/ˈmɑːdəl həˌluːsəˈneɪʃən/",
  factuality: "/ˌfæktʃuˈæləti/",
  faithfulness: "/ˈfeɪθfəlnəs/",
  "confidence calibration": "/ˈkɑːnfədəns ˌkæləˈbreɪʃən/",
  abstention: "/əbˈstɛnʃən/",
  quantization: "/ˌkwɑːntəˈzeɪʃən/",
  PTQ: "/ˌpiː tiː ˈkjuː/",
  pruning: "/ˈpruːnɪŋ/",
  "KV Cache": "/ˌkeɪ viː ˈkæʃ/",
  "memory bandwidth": "/ˈmɛməri ˈbændwɪdθ/",
  "arithmetic intensity": "/ˌærɪθˈmɛtɪk ɪnˈtɛnsəti/",
  "Roofline model": "/ˈruːflaɪn ˈmɑːdəl/",
  "collective communication": "/kəˈlɛktɪv kəˌmjuːnəˈkeɪʃən/",
  AllReduce: "/ˌɔːl rɪˈduːs/",
  ZeRO: "/ˈzɪroʊ/",
  HBM: "/ˌeɪtʃ biː ˈɛm/",
  "inference latency": "/ˈɪnfərəns ˈleɪtənsi/",
  "inference throughput": "/ˈɪnfərəns ˈθruːpʊt/",
  "model deployment": "/ˈmɑːdəl dɪˈplɔɪmənt/",
  "inference engine": "/ˈɪnfərəns ˈɛndʒɪn/",
  "model serving": "/ˈmɑːdəl ˈsɜːrvɪŋ/",
  "compute kernel": "/kəmˈpjuːt ˈkɜːrnəl/",
  profiler: "/ˈproʊfaɪlər/",
  schema: "/ˈskiːmə/",
  "smoke test": "/smoʊk tɛst/",
  "performance warm-up": "/pərˈfɔːrməns ˈwɔːrm ʌp/",
  prompt: "/prɑːmpt/",
  "system prompt": "/ˈsɪstəm prɑːmpt/",
  "context window": "/ˈkɑːntɛkst ˈwɪndoʊ/",
  "tool calling": "/tuːl ˈkɔːlɪŋ/",
  "model monitoring": "/ˈmɑːdəl ˈmɑːnətərɪŋ/",
  "effective throughput": "/ɪˈfɛktɪv ˈθruːpʊt/",
  SLO: "/ˌɛs ɛl ˈoʊ/",
  "data drift": "/ˈdeɪtə drɪft/",
  "concept drift": "/ˈkɑːnsɛpt drɪft/",
  "canary release": "/kəˈnɛri rɪˈliːs/",
  TTFT: "/ˌtiː tiː ɛf ˈtiː/",
  TPOT: "/ˌtiː piː oʊ ˈtiː/",
  prefill: "/ˌpriːˈfɪl/",
  "chunked prefill": "/tʃʌŋkt ˌpriːˈfɪl/",
  "continuous batching": "/kənˈtɪnjuəs ˈbætʃɪŋ/",
  "paged KV cache": "/peɪdʒd ˌkeɪ viː ˈkæʃ/",
  PagedAttention: "/peɪdʒd əˈtɛnʃən/",
  "memory wall": "/ˈmɛməri wɔːl/",
  modality: "/moʊˈdæləti/",
  "multimodal model": "/ˌmʌltiˈmoʊdəl ˈmɑːdəl/",
  encoder: "/ɪnˈkoʊdər/",
  decoder: "/diːˈkoʊdər/",
  FLOPs: "/flɑːps/",
  "data parallelism": "/ˈdeɪtə ˈpærəˌlɛlɪzəm/",
  "tensor parallelism": "/ˈtɛnsər ˈpærəˌlɛlɪzəm/",
  "pipeline parallelism": "/ˈpaɪpˌlaɪn ˈpærəˌlɛlɪzəm/",
  MoE: "/ˌɛm oʊ ˈiː/",
  "Multi-Token Prediction": "/ˌmʌlti ˈtoʊkən prɪˈdɪkʃən/",
  "fixed-size state": "/ˌfɪkst saɪz ˈsteɪt/",
  "linear attention": "/ˈlɪniər əˈtɛnʃən/",
  "state-space model": "/ˈsteɪt speɪs ˈmɑːdəl/",
  "outer product": "/ˈaʊtər ˈprɑːdʌkt/",
  quantile: "/ˈkwɑːntaɪl/",
  softcap: "/ˈsɔːftkæp/",
  "total parameters": "/ˈtoʊtəl pəˈræmɪtərz/",
  "activated parameters": "/ˈæktəveɪtəd pəˈræmɪtərz/",
  "Scaling Laws": "/ˈskeɪlɪŋ lɔːz/",
  "expert parallelism": "/ˈɛkspɜːrt ˈpærəlɛlɪzəm/",
  "context parallelism": "/ˈkɑːntɛkst ˈpærəlɛlɪzəm/",
  "prefix cache": "/ˈpriːfɪks kæʃ/",
  "speculative decoding": "/ˈspɛkjələtɪv diːˈkoʊdɪŋ/",
  "test-time compute": "/ˈtɛst taɪm kəmˈpjuːt/",
  RLVR: "/ˌɑːr ɛl viː ˈɑːr/",
  "reward hacking": "/rɪˈwɔːrd ˈhækɪŋ/",
  "agent harness": "/ˈeɪdʒənt ˈhɑːrnəs/",
  QAT: "/ˌkjuː eɪ ˈtiː/",
  "native multimodal pretraining": "/ˈneɪtɪv ˌmʌltiˈmoʊdəl ˌpriːˈtreɪnɪŋ/",
  "multimodal alignment": "/ˌmʌltiˈmoʊdəl əˈlaɪnmənt/",
  KDA: "/ˌkeɪ diː ˈeɪ/",
  "Gated MLA": "/ˌɡeɪtəd ˌɛm ɛl ˈeɪ/",
  AttnRes: "/əˈtɛn rɛz/",
  "Stable LatentMoE": "/ˈsteɪbəl ˈleɪtənt ˌɛm oʊ ˈiː/",
  "Quantile Balancing": "/ˈkwɑːntaɪl ˈbælənsɪŋ/",
  MOPD: "/ˌɛm oʊ piː ˈdiː/"
}));

const speechOverrides = new Map(Object.entries({
  PCA: "P C A",
  "t-SNE": "T S N E",
  UMAP: "U map",
  MLP: "M L P",
  CNN: "C N N",
  RNN: "R N N",
  LSTM: "L S T M",
  GRU: "G R U",
  GAN: "gan",
  GNN: "G N N",
  "token ID": "token I D",
  SFT: "S F T",
  "large language model": "large language model",
  PEFT: "P E F T",
  GRPO: "G R P O",
  AdamW: "Adam W",
  FLOPs: "flops",
  "LLM-as-a-Judge": "L L M as a judge",
  LoRA: "low rah",
  QLoRA: "Q low rah",
  RLHF: "R L H F",
  DPO: "D P O",
  RAG: "rag",
  "KV Cache": "K V cache",
  HBM: "H B M",
  TTFT: "T T F T",
  TPOT: "T P O T",
  MoE: "M O E",
  "Multi-Token Prediction": "multi token prediction",
  RLVR: "R L V R",
  QAT: "Q A T",
  PTQ: "P T Q",
  KDA: "K D A",
  "Gated MLA": "gated M L A",
  AttnRes: "attention res",
  "Stable LatentMoE": "stable latent M O E",
  MOPD: "M O P D",
  SLO: "S L O",
  AllReduce: "all reduce",
  ZeRO: "zero"
}));

function defineTerm(term, anchor, aliases, summary, misconception, options = {}) {
  return {
    term,
    anchor: `term-${anchor}`,
    aliases,
    summary,
    misconception,
    pronunciation: options.pronunciation ?? pronunciations.get(term) ?? null,
    speech: options.speech ?? speechOverrides.get(term) ?? term,
    audio: options.audio ?? `/pronunciation/${anchor}.wav`,
    visual: options.visual ?? null,
    maxLinksPerPage: options.maxLinksPerPage ?? null,
    href: `${glossaryBase}#term-${anchor}`
  };
}

export const wikiTerms = [
  defineTerm("token", "token", ["token", "词元"], "模型序列中的一个处理单元；文本 token 由 tokenizer 切分，图像或音频模型还可能使用 patch、帧或离散码等 token。", "token 必然等于一个字或一个完整单词，或所有模态都共用文本 tokenizer。"),
  defineTerm("token ID", "token-id", ["token ID", "token IDs"], "token 在固定词表中的离散整数索引，可用于选择 Embedding 行、表示训练目标或标记输出候选。例：‘猫’在某词表中的 token ID 可以是 238。", "token ID 本身是连续语义数值，编号大小代表 token 之间的语义远近。"),
  defineTerm("tokenizer", "tokenizer", ["tokenizer", "分词器"], "负责把文本切成 token，并在 token 与整数 ID 之间转换的规则和词表。", "tokenizer 是模型自己临时决定的切词方式。"),
  defineTerm("BPE", "bpe", ["BPE", "Byte Pair Encoding", "字节对编码"], "一种 tokenizer 训练方法：从基本单元出发，反复合并语料中常见的相邻单元，并保存规则供后续编码使用。", "每次聊天都会根据当前句子重新学习一套合并规则。"),
  defineTerm("vocab", "vocab", ["vocab", "词表"], "tokenizer 可以表示的 token 集合；输出层通常也对这组 token 给出分数。", "词表包含了模型掌握的全部知识。"),
  defineTerm("parameter", "parameter", ["parameter", "parameters", "模型参数"], "模型计算中保存的数值；它们先被初始化，训练可以更新其中允许学习的部分。例：某个权重可以是 -0.017。", "所有参数都会在每次训练中更新，或一个参数对应一条可直接读取的事实。"),
  defineTerm("trainable parameters", "trainable-parameters", ["trainable parameters", "trainable parameter", "可训练参数", "可训练参数量"], "当前训练配置中参与梯度计算并允许优化器更新的参数子集。", "可训练参数量等于模型总参数量，或冻结参数不会参与前向计算。"),
  defineTerm("language model", "language-model", ["language model", "language models", "语言模型"], "为文本或其他符号序列建立概率，并预测下一个、缺失或指定位置内容的模型。", "语言模型必然是聊天机器人，或只能处理自然语言文字。", { maxLinksPerPage: 1 }),
  defineTerm("large language model", "large-language-model", ["large language model", "large language models", "LLM", "LLMs", "大语言模型"], "规模较大、从大量数据训练的神经语言模型；“大”没有跨论文统一参数门槛。", "参数更多就自动更真实、更会推理，或所有 AI 模型都是大语言模型。", { maxLinksPerPage: 1 }),
  defineTerm("neural network", "neural-network", ["neural network", "neural networks", "神经网络"], "由多层可学习变换组成、通过训练调整参数的计算系统。", "神经网络会像人脑一样保存可逐条读取的记忆，或 Transformer 之外的网络都已过时。", { maxLinksPerPage: 1 }),
  defineTerm("model architecture", "model-architecture", ["model architecture", "model architectures", "模型架构"], "规定模型包含哪些层、怎样连接、张量如何流动的计算蓝图。", "架构就是已经训练好的权重文件，或参数量相同就表示架构相同。", { maxLinksPerPage: 1 }),
  defineTerm("model weights", "model-weights", ["model weights", "model weight", "模型权重"], "模型架构中由训练得到并在推理时读取的参数数值。", "一项权重对应一条事实，或加载权重就包含 tokenizer、服务和全部运行配置。", { maxLinksPerPage: 1 }),
  defineTerm("base model", "base-model", ["base model", "base models", "model base", "基座模型", "模型基座"], "在一个项目中作为提示、检索、微调或对齐起点的模型与检查点。", "基座模型必然未经后训练、规模最大或适合所有下游任务。", { maxLinksPerPage: 1 }),
  defineTerm("foundation model", "foundation-model", ["foundation model", "foundation models", "基础模型"], "在广泛数据上训练、可适配多种下游任务的模型类别。", "基础模型一定通用、开放，或“基础”只是参数规模更大。", { maxLinksPerPage: 1 }),
  defineTerm("training sample", "training-sample", ["training sample", "training samples", "训练样本"], "一次训练可处理的输入与目标或监督信息单元。", "一行文本必然就是一个独立样本，或样本必须由人工回答。", { maxLinksPerPage: 1 }),
  defineTerm("dataset", "dataset", ["dataset", "datasets", "数据集"], "按任务、来源和用途组织的一组样本，并应记录版本、许可和切分。", "数据集只是一个文件，或样本越多就一定越好。", { maxLinksPerPage: 1 }),
  defineTerm("corpus", "corpus", ["corpus", "corpora", "训练语料", "文本语料", "语料"], "用于语言分析或训练的大规模文本或多模态材料集合。", "语料天然干净、有授权，并已包含任务所需标签。", { maxLinksPerPage: 1 }),
  defineTerm("training label", "training-label", ["training label", "training labels", "训练标签"], "训练样本中作为预测目标或计分依据的类别、token、数值或结构。", "标签一定由人工填写，或它永远代表无争议真值。", { maxLinksPerPage: 1 }),
  defineTerm("data annotation", "data-annotation", ["data annotation", "data labeling", "数据标注", "人工标注"], "按规则为原始样本补充类别、答案、边界、偏好或其他训练与评测信息。", "标注者之间必然一致，或标注完成就自动没有偏差。", { maxLinksPerPage: 1 }),
  defineTerm("training objective", "training-objective", ["training objective", "training objectives", "训练目标", "优化目标"], "规定训练希望哪些预测或行为获得更低损失或更高奖励的数学目标。", "训练目标等同真实世界全部目标，或 loss 低就证明产品成功。", { maxLinksPerPage: 1 }),
  defineTerm("supervision signal", "supervision-signal", ["supervision signal", "supervision signals", "training signal", "training signals", "监督信号", "训练信号"], "告诉训练过程什么输出更符合目标的信息，可来自标签、数据自身、偏好、奖励或验证器。", "监督信号必须由人工逐条写答案，或有信号就保证信号正确。", { maxLinksPerPage: 1 }),
  defineTerm("self-supervised learning", "self-supervised-learning", ["self-supervised learning", "self supervised learning", "自监督学习"], "从原始数据自身构造预测目标的学习方式，例如用文本后一个 token 监督当前位置。", "自监督等于没有训练目标，或完全不需要数据治理。", { maxLinksPerPage: 1 }),
  defineTerm("forward pass", "forward-pass", ["forward pass", "forward propagation", "前向传播", "前向计算"], "按当前参数从输入逐层计算到预测、logits 或任务输出的过程。", "执行前向传播就会更新权重，或它只发生在推理阶段。", { maxLinksPerPage: 1 }),
  defineTerm("activation", "activation", ["activation", "activations", "activation value", "activation values", "激活值"], "某层或某个算子对当前输入产生的中间数值；它依赖输入和当前参数，不是参数本身。例：一个位置的 activation 可以是形状为 `(1, 4096)` 的向量。", "activation 等同激活函数、模型权重或固定不变的知识。", { maxLinksPerPage: 2 }),
  defineTerm("decode phase", "decode-phase", ["decode phase", "decode forward", "decode 前向", "逐 token decode"], "自回归生成在 prefill 之后的阶段，通常反复执行 decode forward、token 选择、状态追加与停止判断。本课程用“decode 前向”专指其中的模型前向：读取历史 KV Cache，写入新 K/V 并产生 logits。例：基础路径每接受一个 token，通常再执行一轮 decode forward。", "decode phase 在所有资料里都只指模型前向，或 decode 前向就是采样。", { maxLinksPerPage: 2 }),
  defineTerm("gradient descent", "gradient-descent", ["gradient descent", "梯度下降"], "梯度指向目标值局部上升最快的方向；梯度下降沿负梯度方向迭代更新，以尝试降低目标值。", "梯度下降一步就能找到全局最优，或它与 AdamW 等具体优化器完全相同。", { maxLinksPerPage: 1 }),
  defineTerm("hyperparameter", "hyperparameter", ["hyperparameter", "hyperparameters", "超参数"], "由训练配置设定而非模型直接从数据学出的量，例如学习率、batch size 或正则化强度。", "超参数不影响模型结果，或只能凭经验随意选择。", { maxLinksPerPage: 1 }),
  defineTerm("random seed", "random-seed", ["random seed", "random seeds", "随机种子", "seed"], "初始化伪随机过程的整数起点，用于控制数据顺序、初始化或采样等随机来源。例：seed = 42。", "相同 seed 能跨硬件和软件版本保证逐 bit 相同。", { maxLinksPerPage: 1 }),
  defineTerm("gradient accumulation", "gradient-accumulation", ["gradient accumulation", "梯度累积"], "连续汇总多个微批次的梯度后再执行一次优化器更新。", "它与一次放入同样大 batch 在所有模型和实现中严格等价。", { maxLinksPerPage: 1 }),
  defineTerm("mixed precision training", "mixed-precision-training", ["mixed precision training", "mixed-precision training", "混合精度训练", "混合精度"], "在训练中为不同张量或算子选择不同数值精度，并配合缩放和累加管理稳定性。", "所有计算都使用同一种低精度，或显存减少比例必然等于位宽比例。", { maxLinksPerPage: 1 }),
  defineTerm("regularization", "regularization", ["regularization", "正则化"], "用约束、噪声、数据增强或训练策略减少模型只记训练数据的倾向。", "加入正则化就保证泛化，或正则化只指权重衰减。", { maxLinksPerPage: 1 }),
  defineTerm("early stopping", "early-stopping", ["early stopping", "早停"], "根据预先规定的验证指标和耐心窗口停止训练，以避免无收益或过拟合。", "看过测试结果后决定停止仍属于独立测试，或首次波动就应停止。", { maxLinksPerPage: 1 }),
  defineTerm("fitting", "fitting", ["fitting", "拟合"], "根据训练数据调整参数或规则，使模型逼近数据中关系的过程；训练指标改善是可能表现，不等于已经泛化。", "拟合就是训练集分数变好，或拟合得好就证明未见数据也会表现好。", { maxLinksPerPage: 1 }),
  defineTerm("generalization", "generalization", ["generalization", "泛化", "泛化能力"], "模型把训练中学到的规律迁移到未参与拟合的新样本或新情境的能力。", "训练 loss 低就证明泛化好，或一次新样本成功就能代表整体泛化。", { maxLinksPerPage: 1 }),
  defineTerm("data leakage", "data-leakage", ["data leakage", "数据泄漏", "评测泄漏"], "训练、规则拟合或方案选择使用了本应隔离的信息，使评测结果失真。", "只有测试文本直接进入训练参数才算泄漏。", { maxLinksPerPage: 1 }),
  defineTerm("data contamination", "data-contamination", ["data contamination", "benchmark contamination", "数据污染", "评测污染"], "评测题、答案或近重复内容混入训练材料，使模型可能靠见过内容获得高分。", "只要没有完全相同的字符串就一定没有污染。", { maxLinksPerPage: 1 }),
  defineTerm("vector", "vector", ["vector", "vectors", "向量"], "按顺序排列的一组数；维数是坐标数量，向量长度需要由这些数计算。例：[3, 4] 是二维向量，欧氏长度为 5。", "向量有 10 个坐标，就表示它的长度等于 10。", {
    maxLinksPerPage: 2,
    visual: { type: "vector", values: [3, 4, 0, 0, 12], focus: 5, mathLabel: "a₅ = 12", codeLabel: "a[4] = 12", caption: "数学下标通常从 1 开始，Python 索引从 0 开始。" }
  }),
  defineTerm("matrix", "matrix", ["matrix", "matrices", "矩阵"], "按行列组织的一组数；在线性计算中，它可以充当把输入向量变成输出向量的规则。例：[[1, 2], [3, 4]] 是 2 x 2 矩阵。", "矩阵 W 就是输入空间或输出空间本身。", {
    maxLinksPerPage: 2,
    visual: { type: "pipeline", items: ["输入向量 x", "矩阵 W", "输出向量 y"], caption: "x 和 y 是空间中的具体点，W 是连接两个空间的变换规则。" }
  }),
  defineTerm("embedding", "embedding", ["embedding", "embeddings", "词嵌入", "嵌入"], "把对象表示为连续向量；语言模型的 token Embedding 通常通过可训练查表把 token ID 映射成向量。", "所有 embedding 都只能来自 token ID 查表，或每个坐标都有人工指定的固定语义。", {
    visual: { type: "pipeline", items: ["token", "ID 42", "[0.2, -0.7, 1.1]"], caption: "同一内容依次换成离散单元、整数编号和连续向量。" }
  }),
  defineTerm("hidden state", "hidden-state", ["hidden state", "hidden states", "上下文化隐藏状态", "隐藏状态"], "某一层、某一位置结合当前上下文形成的向量表示。", "隐藏状态与静态 token Embedding 永远相同。"),
  defineTerm("hidden dimension", "hidden-dimension", ["hidden dimension", "hidden dimensions", "隐藏维度"], "每个位置的隐藏表示包含的坐标数量，是一个正整数，常记为 D。例：D = 4096 表示每个位置有 4096 个坐标。", "每一维都有固定可命名的人类语义。"),
  defineTerm("tensor", "tensor", ["tensor", "tensors", "张量"], "按若干轴组织的一组数，是向量和矩阵的推广。例：形状 (2, 4, 8) 的三轴张量共含 64 个数。", "张量各轴的含义可以不说明，只看总元素数。"),
  defineTerm("tensor shape", "tensor-shape", ["tensor shape", "tensor shapes", "张量形状"], "各轴长度组成的整数记录，必须连同轴含义一起读。例：(2, 4, 8) 可以表示 2 个样本、每个 4 个 token、每个 token 8 个坐标。", "相同数字排列代表相同轴含义。", {
    visual: { type: "pipeline", items: ["batch = 2", "time = 4", "hidden = 8"], caption: "形状 (2, 4, 8) 的三个数字必须连同轴名称一起读。" }
  }),
  defineTerm("representation space", "representation-space", ["representation space", "representation spaces", "表示空间"], "模型用一组坐标和方向组织隐藏表示的高维空间。", "每个坐标轴都是人工预先定义的概念。"),
  defineTerm("high-dimensional space", "high-dimensional-space", ["high-dimensional space", "high-dimensional spaces", "高维空间"], "需要许多坐标描述一个点或向量的空间。", "高维空间能像二维平面一样完整画出和直观看懂。"),
  defineTerm("vector norm", "vector-norm", ["vector norm", "vector norms", "向量范数"], "把向量总体幅度汇总成非负标量的规则。例：[3, 4] 的欧氏范数是 5。", "向量范数能说明向量具体朝哪个方向。", {
    visual: { type: "pipeline", items: ["[3, 4]", "3² + 4² = 25", "√25 = 5"], caption: "逐个平方、全部相加、最后开方。" }
  }),
  defineTerm("cosine similarity", "cosine-similarity", ["cosine similarity", "余弦相似度"], "用一个标量比较两个非零向量的方向，常见范围为 -1 到 1。例：0.92 表示方向很接近，但不等于语义必然相同。", "余弦相似度等同于欧氏距离或原始点积。"),
  defineTerm("Euclidean distance", "euclidean-distance", ["Euclidean distance", "欧氏距离"], "把两个点之间的直线距离汇总为非负标量。例：(0, 0) 到 (3, 4) 的距离是 5。", "欧氏距离在所有高维表示任务中都天然最合适。"),
  defineTerm("linear projection", "linear-projection", ["linear projection", "linear projections", "线性投影"], "用矩阵学习输入坐标的组合并映射到输出空间。", "线性投影只是 reshape，或输出维度越大知识越多。", {
    visual: { type: "pipeline", items: ["2 个输入坐标", "乘矩阵 W", "3 个输出坐标"], caption: "矩阵学习新的坐标组合，输出维数可以改变。" }
  }),
  defineTerm("subspace", "subspace", ["subspace", "subspaces", "子空间"], "高维空间中由较少独立方向张成的受限空间。", "子空间是从原向量机械切出的一段固定语义坐标。"),
  defineTerm("matrix rank", "matrix-rank", ["matrix rank", "矩阵秩"], "矩阵行空间或列空间的独立方向数量，是一个非负整数。例：2 x 2 单位矩阵的秩为 2。", "矩阵秩就是矩阵元素大小或参数数量。"),
  defineTerm("low rank", "low-rank", ["low rank", "low-rank", "低秩"], "矩阵的秩明显小于其行数与列数上限，说明它能由较少独立方向表示。", "低秩等于数值很小、矩阵稀疏，或一定能在现有硬件上同比加速。"),
  defineTerm("dimensionality reduction", "dimensionality-reduction", ["dimensionality reduction", "降维"], "把高维数据摘要到较少维度以分析、压缩或可视化。", "降维能无损保留高维空间的全部关系。"),
  defineTerm("PCA", "pca", ["PCA", "主成分分析"], "寻找保留较大线性变化方向的降维方法。", "前两个主成分代表全部结构或真实语义轴。"),
  defineTerm("t-SNE", "tsne", ["t-SNE", "tSNE"], "尽量在低维图中保留高维数据的局部邻近关系，常用于探索性可视化。", "二维簇间距离、簇大小和全局方向可直接还原高维结构。"),
  defineTerm("UMAP", "umap", ["UMAP"], "基于邻域图和流形假设构造低维表示的方法。", "UMAP 输出图就是原高维空间的唯一真实地图。"),
  defineTerm("logits", "logits", ["logits", "logit"], "softmax 之前的一组任意实数分数，通常构成与候选数等长的向量。例：三个候选的 logits 可以是 [1.2, -0.3, 2.0]。", "logits 已经是概率或正确率。"),
  defineTerm("softmax", "softmax", ["softmax"], "把分数向量转换为非负且总和为 1 的权重向量的函数。例：softmax([0, 1]) 约为 [0.27, 0.73]。", "softmax 会让模型答案自动真实或概率自动校准。", {
    visual: { type: "bars", items: [{ label: "候选 A", value: 27 }, { label: "候选 B", value: 73 }], caption: "logits [0, 1] 转成约 [0.27, 0.73]。" }
  }),
  defineTerm("loss", "loss", ["loss", "损失函数"], "loss 既可指计算差异的损失函数，也常指该函数在一批数据上算出的标量。例：交叉熵函数算得 loss = 2.31。", "任何信息损失都属于训练 loss，或一个 loss 数值足以代表模型的全部质量。"),
  defineTerm("gradient", "gradient", ["gradient", "gradients", "梯度"], "梯度是 loss 相对当前计算图中参与运算且允许训练的参数的局部变化率，通常是一组与参数形状对应的数；冻结、未参与或梯度已断开的参数可能没有梯度。例：某参数的梯度可以是 0.08。", "每个参数一定都有梯度，或梯度直接给出了全局最优答案。", {
    visual: { type: "pipeline", items: ["参数 5", "减去 0.1 × 2", "新参数 4.8"], caption: "梯度给局部方向，学习率控制迈多大一步。" }
  }),
  defineTerm("gradient norm", "gradient-norm", ["gradient norm", "gradient norms", "梯度范数"], "把一组参数梯度的总体幅度汇总成一个非负标量。例：某一步的 gradient norm = 1.7。", "梯度范数正常就表示每个参数的更新都合理。"),
  defineTerm("learning rate", "learning-rate", ["learning rate", "学习率"], "控制每次参数更新幅度的非负标量超参数。例：learning rate = 2e-5，也就是 0.00002。", "学习率越大，训练一定越快越好。"),
  defineTerm("optimizer", "optimizer", ["optimizer", "优化器"], "根据梯度及内部状态计算参数更新的算法，例如 AdamW。", "优化器负责计算前向预测或损失。"),
  defineTerm("AdamW", "adamw", ["AdamW"], "一种常用优化器：用梯度的一阶与二阶移动统计适配更新尺度，并把权重衰减从梯度适配中解耦。", "会自动找到合适学习率、保证泛化，或负责计算梯度。"),
  defineTerm("batch", "batch", ["batch", "batches", "批次"], "一次共同送入计算流程的一组样本、序列或请求；训练 batch 产生梯度，推理 batch 只执行前向与解码。", "一个 batch 必然等于一次优化器更新或只用于训练。"),
  defineTerm("batch size", "batch-size", ["batch size", "batch sizes", "批次大小"], "一个 batch 包含的样本或序列数量，是一个正整数；训练时还要区分微批次与有效批次。例：batch size = 16。", "batch size 越大就一定训练得更快、更好，或等于一次参数更新使用的全部样本数。"),
  defineTerm("effective batch size", "effective-batch-size", ["effective batch size", "global batch size", "有效批次", "有效批次大小", "全局批次大小"], "一次优化器更新汇总的样本或序列总量。例：4 张卡 x 每卡 8 个样本 x 累积 2 次，effective batch size = 64。", "它在所有任务中都只按样本数计算，或扩大后与小批次训练严格等价。"),
  defineTerm("step", "step", ["step", "steps", "训练步"], "本课程默认指一次优化器更新，日志里通常显示为整数计数。例：step = 300 表示已完成 300 次更新。", "所有框架里的 step 都代表完全相同的事件。"),
  defineTerm("epoch", "epoch", ["epoch", "epochs"], "训练过程大致遍历一遍训练集，通常用整数或小数记录进度。例：epoch = 2 表示大致遍历了两遍。", "一个 epoch 总有固定数量的 step。"),
  defineTerm("context", "context", ["context", "上下文"], "模型本次计算可直接利用的输入与生成历史；文本、图像、音频或工具结果通常先编码成 token 或连续表示。", "放进上下文的信息已经永久写入模型参数，或所有模态都必须先变成文本 token。"),
  defineTerm("Transformer", "transformer", ["Transformer"], "由注意力、MLP、残差连接和归一化等模块组成的一类神经网络架构。", "所有大模型都只能采用同一种 Transformer 结构。"),
  defineTerm("Transformer Block", "transformer-block", ["Transformer Block", "Transformer Blocks"], "Transformer 主干中重复堆叠的计算单元，通常包含注意力、MLP、残差连接与归一化。", "每个 Block 都是完全独立的模型，或所有 Block 的参数共享。"),
  defineTerm("attention", "attention", ["attention", "注意力机制", "注意力"], "根据 Query 与 Key 的匹配权重，对 Value 做加权汇总。", "注意力权重就是完整、可靠的人类可读解释。", {
    visual: { type: "pipeline", items: ["Q 与 K 匹配", "softmax 权重", "加权汇总 V"], caption: "先决定看多少，再把对应内容汇入当前位置。" }
  }),
  defineTerm("self-attention", "self-attention", ["self-attention", "self attention", "自注意力"], "让同一序列中的位置互相产生 Query、Key、Value 并按可见范围汇总信息的注意力。", "每个位置可以无条件读取未来，或注意力权重就是完整因果解释。", { maxLinksPerPage: 1 }),
  defineTerm("positional mechanism", "positional-mechanism", ["positional mechanism", "positional mechanisms", "positional encoding", "position encoding", "位置机制", "位置编码"], "向序列表示提供顺序或相对位置线索的机制，例如位置 Embedding、旋转或注意力偏置。", "位置机制只能是把固定的绝对位置向量加到 token Embedding 上。", {
    maxLinksPerPage: 2,
    visual: { type: "pipeline", items: ["token 表示", "加入顺序线索", "带位置信息的表示"], caption: "具体模型可以用相加、旋转或偏置等不同方式表达顺序。" }
  }),
  defineTerm("normalization", "normalization", ["normalization", "normalisation", "Norm", "归一化"], "按规则调整隐藏表示的尺度或统计量；Transformer 中常见 LayerNorm 与 RMSNorm。", "所有归一化算法计算相同，而且一定放在子层之后。", { maxLinksPerPage: 2 }),
  defineTerm("residual connection", "residual-connection", ["residual connection", "residual connections", "skip connection", "残差连接", "残差路径"], "把子层输入直接加回子层输出，为信息和梯度保留较短通路。", "残差连接会跳过子层计算，或保证深层模型一定稳定。", {
    maxLinksPerPage: 2,
    visual: { type: "pipeline", items: ["输入 x", "子层 F(x)", "x + F(x)"], caption: "子层仍会计算，随后再把原输入加回结果。" }
  }),
  defineTerm("MLP", "mlp", ["MLP", "MLPs", "FFN", "feed-forward network", "feed-forward networks", "前馈网络", "多层感知机"], "在 Transformer Block 中对每个位置分别进行可学习的非线性特征变换。", "MLP 会像注意力一样直接在不同 token 位置之间汇总信息。", {
    maxLinksPerPage: 2,
    visual: { type: "pipeline", items: ["隐藏宽度 D", "扩到 M 并非线性变换", "投影回 D"], caption: "常见 MLP 改变特征宽度，但不直接混合不同序列位置。" }
  }),
  defineTerm("CNN", "cnn", ["CNN", "CNNs", "convolutional neural network", "convolutional neural networks", "卷积神经网络"], "用共享卷积核在局部邻域提取特征的一类神经网络架构。", "CNN 只适用于图片，或卷积核会直接识别完整物体。", { maxLinksPerPage: 1 }),
  defineTerm("RNN", "rnn", ["RNN", "RNNs", "recurrent neural network", "recurrent neural networks", "循环神经网络"], "复用同一递归单元，让隐藏状态随序列步骤持续更新的一类网络。", "每个时间步使用不同参数，或固定状态能无损保存任意长历史。", { maxLinksPerPage: 1 }),
  defineTerm("LSTM", "lstm", ["LSTM", "LSTMs", "long short-term memory", "长短期记忆网络"], "用细胞状态与遗忘、输入、输出等门控制序列信息保留和更新的门控循环网络。", "能永久记住所有历史，或 LSTM 的门是人工设定的硬开关。", { maxLinksPerPage: 1 }),
  defineTerm("GRU", "gru", ["GRU", "GRUs", "gated recurrent unit", "gated recurrent units", "门控循环单元"], "用更新门和重置门维护单一隐藏状态的门控循环网络。", "只是删减版 LSTM 因而效果必然更差，或门更少就保证更快。", { maxLinksPerPage: 1 }),
  defineTerm("autoencoder", "autoencoder", ["autoencoder", "autoencoders", "自编码器"], "用编码器把输入变成瓶颈表示，再由解码器重建输入的架构与训练目标组合。", "重建越好就表示下游语义越好，或训练后必须始终保留解码器。", { maxLinksPerPage: 1 }),
  defineTerm("GAN", "gan", ["GAN", "GANs", "generative adversarial network", "generative adversarial networks", "生成对抗网络"], "让生成器与判别器在相互对抗的目标下共同训练的生成建模框架。", "部署生成时必须同时运行判别器，或判别器分不清就证明样本真实。", { maxLinksPerPage: 1 }),
  defineTerm("diffusion model", "diffusion-model", ["diffusion model", "diffusion models", "扩散模型"], "通过学习逐步去噪，在生成时从噪声反复还原样本的一类生成模型。", "训练是在记住加噪前的原图，或采样步数减少后质量必然不变。", { maxLinksPerPage: 1 }),
  defineTerm("GNN", "gnn", ["GNN", "GNNs", "graph neural network", "graph neural networks", "图神经网络"], "让节点沿图边收集邻居消息并更新表示的一类神经网络。", "图中的边一定正确，或堆叠越多层就能无损利用越远关系。", { maxLinksPerPage: 1 }),
  defineTerm("output head", "output-head", ["output head", "output heads", "language modeling head", "LM Head", "输出头"], "把主干网络的隐藏表示映射到任务输出；语言模型中通常得到词表 logits。", "输出头会直接选出下一个 token，或输出天然校准的概率。", {
    maxLinksPerPage: 2,
    visual: { type: "pipeline", items: ["隐藏状态 D", "输出头", "词表 logits V"], caption: "输出头先产生候选分数，解码策略随后才选择 token。" }
  }),
  defineTerm("causal mask", "causal-mask", ["causal mask", "因果遮罩", "因果掩码"], "在自回归计算中限制每个位置只能读取自己和之前位置的遮罩，训练与推理 prefill 都可能使用。", "它会阻止模型读取当前位置之前的内容，或只在训练阶段存在。"),
  defineTerm("backpropagation", "backpropagation", ["backpropagation", "backprop", "反向传播"], "利用链式法则把输出误差逐层传回并计算梯度。", "反向传播本身就是优化器更新。"),
  defineTerm("cross-entropy", "cross-entropy", ["cross-entropy", "cross entropy", "交叉熵"], "把目标分布与预测分布的差异算成标量的常用损失函数；单一正确类别时是 -log p。例：正确类别概率 p = 0.8 时，loss 约为 0.223。", "交叉熵就是准确率，或所有目标分布下都只需读取一个正确类别。"),
  defineTerm("checkpoint", "checkpoint", ["checkpoint", "checkpoints", "检查点"], "训练过程中保存的状态快照，至少可含模型权重，完整恢复训练时通常还需优化器、调度器和随机状态等。", "每个 checkpoint 都包含完整恢复状态，或天然就是可直接上线的产品。"),
  defineTerm("fine-tuning", "fine-tuning", ["fine-tuning", "fine tuning", "finetuning", "微调"], "从已有模型权重出发，用更聚焦的数据和目标继续训练。", "微调必然只更新少量参数，或适合把频繁变化的事实永久写进模型。", { maxLinksPerPage: 1 }),
  defineTerm("full fine-tuning", "full-fine-tuning", ["full fine-tuning", "full-parameter fine-tuning", "full-parameter SFT", "全参数微调", "全量微调", "全参数 SFT", "全参数SFT"], "在已有模型上继续训练并允许通常全部模型参数更新。在“全参数 SFT”这个组合里，“全参数”描述更新范围，“SFT”描述使用监督示例的训练目标。", "它一定比参数高效微调效果好，或训练显存只由权重决定。", { maxLinksPerPage: 1 }),
  defineTerm("PEFT", "peft", ["PEFT", "parameter-efficient fine-tuning", "parameter efficient fine tuning", "参数高效微调"], "只训练少量新增或选定参数来适配已有模型的一类方法。", "PEFT 等同 LoRA，或参数少就保证无质量损失。", { maxLinksPerPage: 1 }),
  defineTerm("adapter", "adapter", ["adapter", "adapters", "模型适配器", "适配器"], "附加到基座模型上的小型可训练模块或参数集合，用于保存任务适配。", "适配器就是完整模型副本，或加载任意适配器都与基座兼容。", { maxLinksPerPage: 1 }),
  defineTerm("pretraining", "pretraining", ["pretraining", "pre-training", "预训练"], "在面向具体下游任务微调或对齐前，用预训练目标从大规模数据中学习初始参数的阶段。", "预训练一定得到通用模型，或数据越多，回答就必然越真实。"),
  defineTerm("continued pretraining", "continued-pretraining", ["continued pretraining", "continued-pretraining", "继续预训练"], "从已有 checkpoint 出发，继续沿用预训练目标学习新数据，可用于扩展领域、语言、时效或数据分布。", "继续预训练只能使用无标注领域数据，或等同于用问答示例做 SFT。"),
  defineTerm("post-training", "post-training", ["post-training", "post training", "模型后训练", "后训练"], "在已有基座检查点上继续塑造指令遵循、偏好、推理、安全或拒答等行为的一组训练阶段。", "后训练会自动补齐事实知识，并保证所有原有能力不退化。"),
  defineTerm("knowledge distillation", "knowledge-distillation", ["knowledge distillation", "knowledge-distillation", "知识蒸馏", "模型蒸馏", "蒸馏"], "让学生模型学习教师模型提供的回答、概率、中间表示或策略信号。", "蒸馏会复制教师全部参数或保证能力无损。"),
  defineTerm("off-policy distillation", "off-policy-distillation", ["off-policy distillation", "离策略蒸馏"], "让学生在预先收集的教师轨迹或固定数据上学习，训练状态主要由教师或数据集决定。", "固定教师示范与学生推理时会访问的状态完全一致。"),
  defineTerm("on-policy distillation", "on-policy-distillation", ["on-policy distillation", "在策略蒸馏", "OPD"], "学生先生成自己会访问的状态或前缀，再由教师在这些状态上提供概率、回答或其他监督信号。", "在策略一定等于逐 token logit 蒸馏，或教师更强就保证学生学得更好。"),
  defineTerm("exposure bias", "exposure-bias", ["exposure bias", "暴露偏差"], "训练时依赖理想历史，推理时却必须接着自己的输出生成，由此产生的状态分布差异。", "只要单步预测准确，误差就不会沿生成轨迹累积。"),
  defineTerm("teacher model", "teacher-model", ["teacher model", "teacher-model", "教师模型"], "在蒸馏中提供输出、概率、特征或评估信号的模型；它通常更强，但教师身份由监督角色决定。", "教师模型必然更大、更强，或产生的每个答案都是真值。"),
  defineTerm("student model", "student-model", ["student model", "student-model", "学生模型"], "在蒸馏中学习教师信号、通常更小或更便宜的模型。", "学生只能通过复制参数获得教师能力。"),
  defineTerm("logit distillation", "logit-distillation", ["logit distillation", "logit-distillation", "logit 蒸馏"], "让学生匹配教师在候选 token 上的 logits 或软概率分布。", "只要看最终答案就等于获得了教师的完整概率信息。"),
  defineTerm("SFT", "sft", ["SFT", "supervised fine-tuning", "supervised fine tuning", "监督微调", "指令微调", "instruction tuning"], "用输入与理想输出示例进行监督训练，使模型更符合目标行为。", "SFT 会自动完成事实核验，或所有指令微调都使用完全相同的数据和 loss 范围。"),
  defineTerm("LoRA", "lora", ["LoRA"], "冻结大部分基础权重，用低秩矩阵学习权重增量的参数高效微调方法。", "LoRA 会自动压缩推理模型或保证无损。"),
  defineTerm("QLoRA", "qlora", ["QLoRA"], "以低比特形式保存冻结的基础模型，运算时通常反量化到计算精度，同时训练 LoRA 适配器。", "所有训练状态和矩阵乘法都直接使用 4 bit。"),
  defineTerm("RLHF", "rlhf", ["RLHF", "reinforcement learning from human feedback", "人类反馈强化学习"], "利用人类偏好信号和强化学习优化模型行为的一类流程。", "所有对齐都只能通过 RLHF 完成。"),
  defineTerm("DPO", "dpo", ["DPO", "Direct Preference Optimization", "直接偏好优化"], "比较获选与拒选回答相对参考策略的对数概率比，用分类损失直接优化策略；不必先训练显式奖励模型再运行在线强化学习。", "DPO 不需要偏好数据、参考约束或独立评测。"),
  defineTerm("model alignment", "model-alignment", ["model alignment", "AI alignment", "模型对齐"], "让模型行为更符合明确的人类意图、任务规范和安全边界的过程。", "对齐是一种单独算法，或一次训练能代表所有人的价值。", { maxLinksPerPage: 1 }),
  defineTerm("preference data", "preference-data", ["preference data", "preference dataset", "偏好数据"], "记录同一输入下候选输出的选择、排序或理由的数据。", "偏好一定等于事实真值，或标注者之间天然一致。", { maxLinksPerPage: 1 }),
  defineTerm("preference optimization", "preference-optimization", ["preference optimization", "preference tuning", "偏好优化"], "利用候选回答的偏好比较或排序信号调整模型行为的一类后训练方法。", "偏好分数提高就证明事实性、推理和安全都提高。", { maxLinksPerPage: 1 }),
  defineTerm("reward model", "reward-model", ["reward model", "reward models", "奖励模型"], "根据输入和候选输出估计奖励分数、近似某类偏好或任务标准的模型。", "奖励模型是无偏真值裁判，或高奖励必然等于真实成功。", { maxLinksPerPage: 1 }),
  defineTerm("reinforcement learning", "reinforcement-learning", ["reinforcement learning", "强化学习"], "利用带奖励的轨迹数据优化策略的一类学习方法；轨迹可以在线采样，也可以预先收集。", "强化学习就是随机试错，或只要有奖励分数就一定需要强化学习。", { maxLinksPerPage: 1 }),
  defineTerm("policy model", "policy-model", ["policy model", "policy network", "策略模型", "策略网络"], "在强化学习或生成任务中根据当前状态产生动作或 token 分布、并被优化的模型。", "策略模型等同奖励模型，或这里的策略只是部署规则。", { maxLinksPerPage: 1 }),
  defineTerm("advantage estimate", "advantage-estimate", ["advantage estimate", "advantage estimation", "优势估计"], "估计某个动作或输出相对参考水平好多少，用于降低方差或指导策略更新。", "优势就是原始奖励、绝对正确率或跨任务可直接比较的分数。", { maxLinksPerPage: 1 }),
  defineTerm("rollout", "rollout", ["rollout", "rollouts", "生成轨迹", "采样轨迹"], "从初始状态出发，记录策略产生的 token 或动作，以及环境或验证器返回的观察、结果、奖励。", "最终答案相同就表示中间轨迹、成本和风险相同。", { maxLinksPerPage: 1 }),
  defineTerm("verifier", "verifier", ["verifier", "verifiers", "验证器", "任务验证器"], "用规则、程序、工具结果或模型检查输出是否满足某些可执行条件的组件。", "验证器覆盖了真实目标的全部边界，或验证通过就等于事实正确。", { maxLinksPerPage: 1 }),
  defineTerm("GRPO", "grpo", ["GRPO", "Group Relative Policy Optimization", "组相对策略优化"], "用同一输入的一组输出及其相对奖励估计策略更新信号的一类方法。", "GRPO 不需要奖励设计和参考约束，或在所有任务上普遍优于其他策略优化方法。"),
  defineTerm("regression test set", "regression-test-set", ["regression test set", "regression set", "回归测试集", "能力回归集"], "用于检查新版本是否破坏旧能力、已修复问题或高风险边界的固定样本集合。", "只保留新任务样本就能发现全部退化，或回归集可以替代独立测试集。", { maxLinksPerPage: 1 }),
  defineTerm("RAG", "rag", ["RAG", "检索增强生成"], "先检索外部资料，再把相关片段放进上下文辅助生成。", "检索到资料就能保证资料和答案都真实。"),
  defineTerm("Agent", "agent", ["Agent", "智能体"], "围绕目标反复观察状态、选择动作并处理结果的系统；大模型 Agent 常借助工具与外部环境交互。", "只要接入一个工具就成为 Agent，或 Agent 可以脱离权限、预算和人工确认自主执行。"),
  defineTerm("Agent Swarm", "agent-swarm", ["Agent Swarm"], "多个 Agent 协作方案的宽泛称呼，常包含任务分解、角色分工、消息协议、结果合并与验收，但没有统一固定架构。", "Agent Swarm 是一个定义统一的算法，或 Agent 越多就一定越快、越可靠。"),
  defineTerm("inference", "inference", ["inference", "模型推理", "推理阶段"], "使用已训练参数对输入执行前向计算，并按任务需要解码或读取预测结果；通常不更新模型权重。", "模型推理等同于推理能力，或推理阶段通常会继续训练模型权重。"),
  defineTerm("model routing", "model-routing", ["model routing", "model router", "模型路由", "路由器"], "按任务复杂度、工具需求、预算或服务状态，在多个模型、版本或运行档位之间选择的一层系统策略。", "用户看到一个模型名称就能证明每次请求都使用同一权重，或路由器必然准确。", { maxLinksPerPage: 1 }),
  defineTerm("model fallback", "model-fallback", ["model fallback", "service fallback", "模型回退", "服务回退"], "首选模型、区域或服务不可用时，按预设条件切换到备用模型或较低成本档位的策略。", "发生回退就一定是厂商故意降级，或回退不会影响质量和工具能力。", { maxLinksPerPage: 1 }),
  defineTerm("model deployment", "model-deployment", ["model deployment", "模型部署"], "把权重、Tokenizer、推理配置、服务和回滚方案交付到目标环境的过程。", "上传一个权重文件就完成部署，或部署后模型会自动持续学习。", { maxLinksPerPage: 1 }),
  defineTerm("inference engine", "inference-engine", ["inference engine", "inference runtime", "推理引擎", "推理运行时"], "在硬件上加载模型并执行算子、缓存、批处理和解码循环的软件运行层。", "推理引擎决定模型知识质量，或换引擎就等于重新训练模型。", { maxLinksPerPage: 1 }),
  defineTerm("model serving", "model-serving", ["model serving", "inference service", "推理服务", "模型服务"], "把模型推理包装为可处理请求、并发、队列、超时、版本和错误的服务系统。", "模型服务只是一个 HTTP 接口，或吞吐提高就代表每个请求更快。", { maxLinksPerPage: 1 }),
  defineTerm("compute kernel", "compute-kernel", ["compute kernel", "kernel function", "计算内核", "算子内核"], "在目标处理器上执行一个具体张量算子或其一部分的底层程序单元，例如矩阵乘法 kernel。它是实现层，不是新的模型参数或算法目标。例：一次 attention kernel 可以读取 Q/K/V 张量并写出中间结果。", "kernel 就是整个模型、操作系统内核，或写出 kernel 就一定得到最佳性能。", { maxLinksPerPage: 1 }),
  defineTerm("profiler", "profiler", ["profiler", "profiling tool", "性能分析器", "性能剖析器"], "记录程序各阶段耗时、显存、调用关系或硬件利用率的分析工具，用来定位实际瓶颈。例：profiler 显示某个 kernel 占总 GPU 时间的 38%。", "profiler 只看模型质量，或一次 profile 就能代表所有输入和并发。", { maxLinksPerPage: 1 }),
  defineTerm("schema", "schema", ["schema", "JSON schema", "结构约束", "数据结构定义"], "描述数据字段、类型、必填项和嵌套关系的结构约束。例：schema 规定 `answer` 必须是字符串、`score` 必须是数字。", "schema 会验证事实正确性，或声明字段就等于执行了工具。", { maxLinksPerPage: 1 }),
  defineTerm("smoke test", "smoke-test", ["smoke test", "smoke tests", "冒烟测试"], "用少量、快速、关键路径样例确认程序能启动并完成基本流程的测试。例：smoke test 检查模型能加载、输入一条请求并返回合法输出。", "smoke test 覆盖了完整质量、性能和安全评测，或通过就证明可以上线。", { maxLinksPerPage: 1 }),
  defineTerm("performance warm-up", "performance-warm-up", ["performance warm-up", "runtime warm-up", "benchmark warm-up", "性能预热"], "正式测量前先运行若干次，让编译、内存分配、缓存和频率等运行状态稳定的步骤。它不同于训练中的 learning-rate warm-up。例：先预热 10 次，再统计后续 100 次 TPOT。", "预热会训练模型、改变权重，或预热次数在所有硬件上都固定有效。", { maxLinksPerPage: 1 }),
  defineTerm("prompt", "prompt", ["prompt", "prompts", "提示词", "模型提示词"], "本次交给模型的指令、上下文、示例或问题组合。", "提示词会永久改变模型权重，或措辞技巧可以补齐模型没有的知识和工具权限。", { maxLinksPerPage: 1 }),
  defineTerm("system prompt", "system-prompt", ["system prompt", "system prompts", "系统提示", "系统提示词"], "应用放在系统消息位置、用于约束角色和行为的提示内容。", "系统提示是不可绕过的安全边界，或已经写入模型参数。", { maxLinksPerPage: 1 }),
  defineTerm("context window", "context-window", ["context window", "context windows", "上下文窗口"], "一次模型计算允许接收和保留的 token 范围及其长度上限口径，通常用 token 数表示。例：128 Ki tokens = 128 x 1024 = 131072 个 token；若文档写 128K，需先确认计量口径。", "支持更长窗口就表示每个位置都能同样可靠利用，或窗口内容会永久保存。", { maxLinksPerPage: 1 }),
  defineTerm("context compaction", "context-compaction", ["context compaction", "context summarization", "上下文压缩", "上下文摘要"], "接近上下文上限时，用摘要或压缩块替换较早内容以继续长任务的策略；压缩可能丢失细节并产生额外 token 成本。", "压缩是无损永久记忆，或摘要存在就代表原始证据仍然可逐字恢复。", { maxLinksPerPage: 1 }),
  defineTerm("tool calling", "tool-calling", ["tool calling", "function calling", "工具调用", "函数调用"], "模型按约定产生工具名称和参数，再由外部系统校验并执行的交互方式。", "模型输出调用参数就表示工具已经执行，或工具返回一定可信。", { maxLinksPerPage: 1 }),
  defineTerm("model monitoring", "model-monitoring", ["model monitoring", "模型监控"], "持续观察模型及其应用系统的服务健康、输出质量、任务效果和安全风险。", "监控只看服务器是否存活，或用户点赞可以直接当真值。", { maxLinksPerPage: 1 }),
  defineTerm("reasoning", "reasoning", ["reasoning", "推理能力", "推理过程"], "为得到结论而组合条件、执行中间步骤或验证结果的能力或过程；它与运行模型的 inference 不是同一概念。", "输出很长的思维链就证明内部推理正确、完整且忠实。"),
  defineTerm("reasoning effort", "reasoning-effort", ["reasoning effort", "reasoning_effort", "推理强度", "推理努力"], "厂商用于引导模型在一次请求中投入多少内部推理 token 或计算预算的控制项；支持值和默认值随模型变化。例：某模型记录为 `reasoning.effort = high`。", "它是行业统一的智商旋钮，或调高后必然得到正确答案。", { maxLinksPerPage: 1 }),
  defineTerm("thinking budget", "thinking-budget", ["thinking budget", "思考预算", "思考 token 预算"], "允许内部思考、搜索、验证或工具循环消耗的 token/计算上限。例：一次请求给思考阶段 256 个 token 的教学预算。", "预算等于模型参数量、知识量，或预算用完就代表答案已经正确。", { maxLinksPerPage: 1 }),
  defineTerm("thinking level", "thinking-level", ["thinking level", "思考级别", "思考档位"], "某些厂商对动态思考量提供的离散或连续控制；具体等级和含义由模型文档定义。例：Gemini 文档中的 `thinking_level`。", "不同厂商的同名 level 可直接比较，或 level 只改变 temperature。", { maxLinksPerPage: 1 }),
  defineTerm("adaptive thinking", "adaptive-thinking", ["adaptive thinking", "自适应思考"], "根据请求复杂度或运行状态动态分配思考量的策略，而不是每个请求使用固定预算。", "自适应就能正确判断所有问题难度，或思考量变化不影响延迟和成本。", { maxLinksPerPage: 1 }),
  defineTerm("decoding strategy", "decoding-strategy", ["decoding strategy", "解码策略", "token sampling", "token 采样"], "根据模型 logits 选择下一个 token 的规则，例如 greedy、temperature、top-k 或 top-p。", "解码策略负责产生模型没有学到的新知识，或随机性是幻觉的唯一原因。"),
  defineTerm("greedy decoding", "greedy-decoding", ["greedy decoding", "贪心解码"], "每一步都选择当前分数或概率最高 token 的确定性解码规则。", "局部每步最高就保证整段序列全局最好或事实正确。"),
  defineTerm("top-k sampling", "top-k-sampling", ["top-k sampling", "top-k 采样"], "每一步只保留分数最高的固定 k 个候选，再在其中采样。", "固定 k 能保证每一步保留相同概率质量。"),
  defineTerm("top-p sampling", "top-p-sampling", ["top-p sampling", "top-p 采样", "nucleus sampling"], "每一步保留累计概率达到阈值 p 的最小高概率候选集合，再在其中采样。", "候选数量固定，或降低 p 就能保证事实正确。"),
  defineTerm("overfitting", "overfitting", ["overfitting", "过拟合"], "模型继续改善训练数据表现，却不能同步改善未见数据表现的现象。", "训练 loss 下降就一定没有过拟合。"),
  defineTerm("catastrophic forgetting", "catastrophic-forgetting", ["catastrophic forgetting", "灾难性遗忘"], "模型学习新任务或新分布后，原有能力显著退化的现象。", "只要新任务分数上升，就不需要检查旧能力。"),
  defineTerm("training set", "training-set", ["training set", "training data", "训练数据集", "训练集"], "用于拟合参数或训练数据相关规则的数据；它产生训练信号，不能同时充当独立最终评估。", "训练集表现好就证明模型能泛化到真实任务。"),
  defineTerm("validation set", "validation-set", ["validation set", "validation data", "验证数据", "验证集", "开发集"], "不直接用于梯度更新，主要用于选配置、checkpoint、阈值或停止时机的数据。", "反复针对验证集调参后，它仍是无偏的最终测试证据。"),
  defineTerm("test set", "test-set", ["test set", "test data", "测试数据集", "测试集"], "在方案和选择规则冻结后用于最终估计的数据；若据此反复改方案，它就参与了开发。", "只要样本不参与梯度更新，就可以无限次查看并一直称为独立测试集。"),
  defineTerm("baseline", "baseline", ["baseline", "model baseline", "模型基线"], "在采用更复杂方法前保存的可比较起点，例如规则、提示或未微调模型。", "基线只是临时演示，方法升级后就可以丢弃。", { maxLinksPerPage: 1 }),
  defineTerm("model evaluation", "model-evaluation", ["model evaluation", "model evaluations", "模型评测", "模型评估"], "在固定样本、规则、预算和版本下收集模型质量、成本与风险证据的过程。", "跑一个排行榜或看几个生成样例就完成了模型评测。", { maxLinksPerPage: 1 }),
  defineTerm("benchmark", "benchmark", ["benchmark", "benchmarks", "基准测试", "评测基准"], "用于可重复比较的一组固定任务、数据、指标和运行口径。", "Benchmark 排名能代表所有真实场景，或不同版本和提示下的分数可直接比较。", { maxLinksPerPage: 1 }),
  defineTerm("ablation study", "ablation-study", ["ablation study", "ablation studies", "ablation experiment", "消融实验", "消融研究"], "通过移除或替换一个关键因素，观察结果变化以缩小贡献归因。", "一次消融能证明完整因果，或组合系统中其他变量都自动不变。", { maxLinksPerPage: 1 }),
  defineTerm("ground truth", "ground-truth", ["ground truth", "ground-truth", "参考真值", "任务真值"], "当前任务认可的参考答案、标签或可核验事实，用于训练或评测。", "所有开放问题都有唯一无争议真值，或标签文件一定正确。", { maxLinksPerPage: 1 }),
  defineTerm("model card", "model-card", ["model card", "model cards", "模型卡"], "记录模型版本、用途、训练与评测信息、限制和风险的说明材料。", "填写模型卡就自动证明模型安全、可复现或适合上线。", { maxLinksPerPage: 1 }),
  defineTerm("data card", "data-card", ["data card", "data cards", "数据卡"], "记录数据来源、许可、组成、处理、切分、已知偏差和适用边界的说明材料。", "数据卡可以替代实际来源核验、样本检查和许可审查。", { maxLinksPerPage: 1 }),
  defineTerm("LLM-as-a-Judge", "llm-as-a-judge", ["LLM-as-a-Judge", "LLM as a Judge", "大模型裁判"], "让大语言模型依据量表评审候选输出，以扩展人工评测的一种方法。", "裁判模型天然无偏、等同人工真值，或不需要顺序交换和人工校准。", { maxLinksPerPage: 1 }),
  defineTerm("pass@k", "pass-at-k", ["pass@k"], "衡量同一任务允许 k 个候选时至少一个通过测试的概率；常从每题采样的 n 个候选中估计，且需满足 n 不小于 k。", "pass@k 等于单个候选正确率，或 pass@10 为 90% 就表示每次生成都有 90% 正确。"),
  defineTerm("model hallucination", "model-hallucination", ["model hallucination", "模型幻觉"], "模型生成了缺少事实依据、违背给定证据或虚构任务状态的内容；具体评测需先说明采用哪种口径。", "模型幻觉只由随机采样造成，关闭 temperature 就能彻底解决。"),
  defineTerm("factuality", "factuality", ["factuality", "事实性"], "回答中的可核验主张与外部事实是否一致。", "事实正确就表示回答一定忠于当前给定证据。"),
  defineTerm("faithfulness", "faithfulness", ["faithfulness", "证据忠实度", "回答忠实度"], "回答中的主张是否得到当前给定证据或工具结果支持。", "忠于证据就能证明证据本身真实、最新且完整。"),
  defineTerm("confidence calibration", "confidence-calibration", ["confidence calibration", "置信度校准", "模型校准"], "先定义可计算的置信分数，再让相近分数样本的长期正确率与该分数更匹配。", "模型措辞更肯定就代表置信分数更高，或校准能把未知事实变成正确答案。"),
  defineTerm("abstention", "abstention", ["abstention", "selective prediction", "选择性回答", "模型拒答"], "当证据或置信不足时选择不作答，并在错误风险与覆盖率之间取舍。", "拒答越多就一定越可靠，或拒答能消除底层错误。"),
  defineTerm("quantization", "quantization", ["quantization", "量化"], "用较少 bit 表示或计算权重、激活等数值，常降低存储和数据搬运成本；实际加速取决于格式、算子与硬件。", "位宽缩小多少就一定同比加速，而且完全没有质量变化。"),
  defineTerm("PTQ", "ptq", ["PTQ", "post-training quantization", "训练后量化"], "不再训练模型参数，而是在训练完成后用权重统计或校准数据确定低比特部署表示。例：将 BF16 权重转换为 4-bit 权重文件。", "不需要校准和任务评测，或所有模型都能无损量化。"),
  defineTerm("pruning", "pruning", ["pruning", "structured pruning", "结构化剪枝", "剪枝"], "删除权重、通道、头或层等部分结构以降低模型规模或计算。", "出现很多零就一定能在目标硬件上变快。"),
  defineTerm("KV Cache", "kv-cache", ["KV Cache", "KV 缓存"], "自回归生成时按层缓存历史位置已计算的 Key/Value，避免后续步骤重复计算这些旧位置的 K/V。", "KV Cache 保存事实知识、会更新模型参数，或主要用于降低训练显存。"),
  defineTerm("memory bandwidth", "memory-bandwidth", ["memory bandwidth", "内存带宽", "显存带宽"], "单位时间内处理器与某级内存可传输的数据量；在 GPU 语境常特指与 HBM/显存之间的带宽。", "内存带宽与内存容量、计算峰值或所有层级的实际有效带宽是同一个指标。"),
  defineTerm("arithmetic intensity", "arithmetic-intensity", ["arithmetic intensity", "算术强度"], "在指定内存层级下，计算操作量与数据搬运字节数之比，常以 FLOP/byte 表示。", "算术强度不需要说明内存层级，或数值越高就保证实际速度越快。"),
  defineTerm("Roofline model", "roofline-model", ["Roofline model", "Roofline 模型", "Roofline"], "把峰值计算能力与带宽乘算术强度两条上限放在同一性能图中的分析模型。", "它能脱离真实测量，直接给出唯一优化方案。"),
  defineTerm("collective communication", "collective-communication", ["collective communication", "集合通信"], "多设备共同参与的数据交换操作族，例如规约、聚合、广播和全互换。", "用了多卡后，通信成本会自动被计算完全隐藏。"),
  defineTerm("AllReduce", "allreduce", ["AllReduce", "all-reduce", "全规约"], "把各设备上的对应数据规约，并把完整结果返回每个参与设备。", "它只是把每张卡的数据集中到一张卡。"),
  defineTerm("ZeRO", "zero", ["ZeRO", "Zero Redundancy Optimizer"], "通过分片优化器状态、梯度和参数，减少数据并行训练中的重复显存占用。", "ZeRO 阶段越高就必然训练越快。"),
  defineTerm("HBM", "hbm", ["HBM", "High Bandwidth Memory", "高带宽内存"], "靠近加速器、为高吞吐数据访问设计的高带宽内存。", "HBM 容量越大就自动代表所有训练和推理都更快。"),
  defineTerm("inference latency", "inference-latency", ["inference latency", "推理延迟"], "一次推理请求从进入系统到产生所需结果所经历的时间，需要说明统计口径和负载。例：完整回答延迟 = 1.8 秒。", "平均延迟足以代表首 token、每 token 和尾延迟体验。"),
  defineTerm("inference throughput", "inference-throughput", ["inference throughput", "推理吞吐", "token throughput", "token 吞吐"], "单位时间内完成的请求数或处理的 token 数，必须说明 token 口径、并发和负载。例：输出吞吐 = 8000 token/s。", "不同 token 口径可以直接比较，或吞吐越高就代表每个用户等待越短。"),
  defineTerm("effective throughput", "effective-throughput", ["effective throughput", "goodput", "有效吞吐"], "只统计同时满足质量、延迟、错误率等服务约束的有效工作量。", "总 tokens/s 上升就必然代表有效吞吐上升。"),
  defineTerm("SLO", "slo", ["SLO", "service level objective", "服务等级目标"], "在指定负载和统计窗口内，对服务指标设定的目标，例如“99% 请求的 TTFT 小于 1 秒”。", "TTFT 等指标本身就是 SLO，或只写“响应要快”就足够验证。"),
  defineTerm("data drift", "data-drift", ["data drift", "数据漂移"], "线上输入的分布相对基准发生变化，例如语言、长度、主题或用户群比例改变。", "检测到数据漂移就证明模型已经失效，或一定需要重新训练。"),
  defineTerm("concept drift", "concept-drift", ["concept drift", "概念漂移"], "输入与正确目标之间的关系发生变化，例如新政策使同一问题有了不同正确答案。", "只要输入样式或流量比例改变就属于概念漂移。"),
  defineTerm("canary release", "canary-release", ["canary release", "canary deployment", "灰度发布"], "让少量真实流量先使用新版本，并依据预设停止条件决定放量或回滚。", "少量流量会自动消除高风险操作，因此不需要权限和安全红线。"),
  defineTerm("capability regression", "capability-regression", ["capability regression", "能力回归", "能力退化"], "新版本在旧版本已经通过的能力、边界或安全样本上出现可重复的显著退化。", "一两个失败样例就能证明模型整体退化，或只看总平均分就能定位原因。", { maxLinksPerPage: 1 }),
  defineTerm("TTFT", "ttft", ["TTFT", "time to first token", "首 token 延迟"], "生成请求从进入系统到返回第一个输出 token 的时长。例：TTFT = 320 ms。", "TTFT 能代表后续每个 token 的生成速度。"),
  defineTerm("TPOT", "tpot", ["TPOT", "time per output token", "每 token 延迟"], "首 token 之后，每生成一个输出 token 的平均时长。例：TPOT = 25 ms/token。", "TPOT 包含全部排队、检索和首轮 prefill 时间。"),
  defineTerm("prefill", "prefill", ["prefill", "prompt prefill", "预填充阶段"], "推理时处理输入上下文、为各层建立 KV Cache 并产生首个待解码位置 logits 的阶段。", "prefill 会一次生成完整回答，或它与逐 token decode 是同一性能阶段。"),
  defineTerm("chunked prefill", "chunked-prefill", ["chunked prefill", "chunked-prefilling", "分块预填充"], "把长输入的 prefill 拆到多个调度步，使它能与正在 decode 的请求共享执行预算。", "切块只改变调度，不需要检查实现语义、延迟或吞吐权衡。"),
  defineTerm("continuous batching", "continuous-batching", ["continuous batching", "连续批处理"], "推理服务根据请求到达与完成动态调整 batch，使设备持续处理可运行请求。", "连续批处理必然同时降低单请求延迟并提高吞吐。"),
  defineTerm("paged KV cache", "paged-kv-cache", ["paged KV cache", "分页 KV Cache", "分页 KV 缓存"], "把 KV Cache 划成块并用映射表管理其物理存放，以减少碎片、支持共享或动态分配。", "分页会自动减少每个 token 的 KV 内容，或分页 KV Cache 与 PagedAttention 是任何语境下都可互换的同义词。"),
  defineTerm("PagedAttention", "paged-attention", ["PagedAttention"], "vLLM 提出的注意力实现，让算子通过块表读取非连续存放的分页 KV Cache；它与缓存管理紧密配合，但不是所有分页缓存的通用名称。", "PagedAttention 是一种新的模型注意力语义，或只是 paged KV cache 的任意同义写法。"),
  defineTerm("memory wall", "memory-wall", ["memory wall", "内存墙"], "计算速度提升后，数据搬运速度成为整体性能主要限制的现象。", "内存墙只是显存容量不足，换更大容量就一定解决。"),
  defineTerm("modality", "modality", ["modality", "modalities", "模态"], "信息的表现与采集形式，例如文本、图像、语音或视频。", "文件扩展名相同就一定是同一模态任务，或所有模态都能直接共用文本 token。", { maxLinksPerPage: 1 }),
  defineTerm("multimodal model", "multimodal-model", ["multimodal model", "multimodal models", "多模态模型"], "能联合处理或生成两种及以上模态表示的模型或模型系统。", "接入 OCR 就自动成为端到端多模态模型，或所有模态共用同一编码器和输出头。", { maxLinksPerPage: 1 }),
  defineTerm("encoder", "encoder", ["encoder", "encoders", "编码器", "模态编码器"], "把输入转换成主干或下游任务可处理表示的网络或算法组件。", "编码器已经完成全部理解、推理和生成，或所有编码器都是 Transformer Encoder。", { maxLinksPerPage: 1 }),
  defineTerm("decoder", "decoder", ["decoder", "decoders", "解码器", "模态解码器"], "把隐藏表示还原、预测或生成到目标输出空间的组件。", "解码器只指 Decoder-only Transformer，或必然逐 token 输出文字。", { maxLinksPerPage: 1 }),
  defineTerm("FLOPs", "flops", ["FLOPs", "floating-point operations", "浮点运算量"], "完成某段计算所需浮点操作数量的计数，常用于估算计算规模。例：1 TFLOP 表示 10^12 次浮点操作，不表示耗时 1 秒。", "FLOPs 就是每秒速度、运行时长或跨实现可直接比较的实际成本。", { maxLinksPerPage: 1 }),
  defineTerm("data parallelism", "data-parallelism", ["data parallelism", "data parallel", "数据并行"], "让不同设备处理不同样本或 batch 分片，并在更新前同步梯度或等价状态。", "每张设备只保存模型的一部分，或设备数翻倍就线性加速。", { maxLinksPerPage: 1 }),
  defineTerm("tensor parallelism", "tensor-parallelism", ["tensor parallelism", "tensor parallel", "张量并行"], "把同一层的大张量计算切分到多个设备协同完成。", "它就是数据并行，或切分后不需要设备间通信。", { maxLinksPerPage: 1 }),
  defineTerm("pipeline parallelism", "pipeline-parallelism", ["pipeline parallelism", "pipeline parallel", "流水线并行"], "把不同层或阶段分到不同设备，并让多个微批次像流水线一样推进。", "各阶段总能完全均衡，或流水线没有气泡和激活通信。", { maxLinksPerPage: 1 }),
  defineTerm("MoE", "moe", ["MoE", "Mixture of Experts", "混合专家"], "由路由器组合多个专家子网络的架构；现代大模型常用稀疏 MoE，让每个 token 只激活部分专家。", "所有 MoE 都必须稀疏激活，或它是多个完整模型对同一答案投票。"),
  defineTerm("Multi-Token Prediction", "multi-token-prediction", ["Multi-Token Prediction", "MTP"], "让一个训练位置获得多个未来 token 的预测监督的一类方法，可由并行预测头、串联预测模块等实现；部分实现也能在推理时提供多 token 候选。", "所有 MTP 都采用同一种结构，或训练时预测多个位置就等于推理时一次接受多个正确 token。"),
  defineTerm("fixed-size state", "fixed-size-state", ["fixed-size state", "固定状态", "固定形状状态"], "用相对序列长度不增长的状态递推压缩历史，而不是为每个 token 保留一份独立缓存。", "固定大小表示与 batch、层数等所有因素无关，或能无损记住无限历史。"),
  defineTerm("linear attention", "linear-attention", ["linear attention", "线性注意力"], "把注意力改写为可递推或可重排的状态计算，使部分成本对序列长度近似线性。", "所有线性注意力都无损等价于 softmax 注意力。"),
  defineTerm("state-space model", "state-space-model", ["state-space model", "state space model", "SSM", "状态空间模型"], "用状态递推处理序列的一类模型，常以固定形状状态压缩历史。", "状态空间模型自动保留任意长度历史的全部细节。"),
  defineTerm("outer product", "outer-product", ["outer product", "外积"], "把两个向量组合成矩阵，常用于把键方向与值内容写入状态。", "外积与得到单个标量的点积相同。"),
  defineTerm("quantile", "quantile", ["quantile", "quantiles", "分位数"], "按排序位置描述数据分布阈值的统计量；具体插值口径需明确。", "分位数在所有软件和样本规模下只有一种计算定义。"),
  defineTerm("softcap", "softcap", ["softcap", "平滑封顶"], "用平滑函数限制数值幅度，同时保留连续梯度。", "封顶后就自动没有溢出、稳定性或质量问题。"),
  defineTerm("total parameters", "total-parameters", ["total parameters", "总参数量"], "模型包含的全部参数元素数量，不论当前训练是否冻结；稀疏 MoE 中也包括本 token 未选择的专家。例：70B 表示约 700 亿个参数。", "总参数量等于可训练参数量，或等于每个 token 实际经过的参数量。"),
  defineTerm("activated parameters", "activated-parameters", ["activated parameters", "激活参数", "激活参数量"], "稀疏模型一次 token 前向实际使用的参数数量口径，通常包含共享部分与被选专家。例：总参数 100B 的教学 MoE 可以每 token 只激活 10B。", "它有跨论文唯一口径，或可直接当作精确 FLOPs、延迟或完整显存占用。"),
  defineTerm("Scaling Laws", "scaling-laws", ["Scaling Laws", "scaling law", "scaling laws", "缩放定律"], "在限定数据、模型与计算范围内观察到的经验缩放关系。", "参数翻倍就保证能力按固定比例增长。"),
  defineTerm("expert parallelism", "expert-parallelism", ["expert parallelism", "专家并行"], "把 MoE 专家分布到不同设备，并按路由交换 token 的并行方式。", "只减少计算而不会引入通信或负载不均。"),
  defineTerm("context parallelism", "context-parallelism", ["context parallelism", "上下文并行"], "把同一长序列的不同片段分到多个设备协同计算。", "与把不同样本分给设备的数据并行相同。"),
  defineTerm("prefix cache", "prefix-cache", ["prefix cache", "prefix caching", "前缀缓存"], "在模型、执行配置、token 与位置信息兼容时，复用相同前缀已计算的中间状态。", "文本看起来相似、模型版本不同或权限隔离的请求也能直接复用。"),
  defineTerm("speculative decoding", "speculative-decoding", ["speculative decoding", "推测解码"], "由草稿模型提出候选，再由目标模型批量验证；满足相应接受规则时可保持目标模型的输出分布。", "所有推测解码都天然无损，或草稿模型可以绕过目标模型直接决定输出。"),
  defineTerm("test-time compute", "test-time-compute", ["test-time compute", "test time compute", "测试时计算", "推理时计算"], "在推理阶段增加采样、搜索、验证或思考预算，以换取任务质量。", "增加推理预算就等于改变了模型训练参数。"),
  defineTerm("RLVR", "rlvr", ["RLVR", "reinforcement learning with verifiable rewards", "可验证奖励强化学习"], "使用程序或明确验证器产生奖励来训练策略的一类强化学习方法。", "验证器给出的高分必然等于真实任务完成。"),
  defineTerm("reward hacking", "reward-hacking", ["reward hacking", "奖励投机"], "策略利用奖励或验证器漏洞拿到高分，却没有完成真实目标。", "分数提高就一定代表任务能力提高。"),
  defineTerm("agent harness", "agent-harness", ["agent harness"], "包围模型的系统提示、工具、执行循环、上下文管理与错误恢复机制。", "排行榜中的 Agent 成绩只反映基础模型权重。"),
  defineTerm("QAT", "qat", ["QAT", "quantization-aware training", "量化感知训练"], "训练时模拟目标低精度数值效果，让参数适应部署格式。例：训练中模拟 8-bit 线性层，再导出 8-bit 权重。", "所有组件都必须使用同一种低比特格式且不会掉点。"),
  defineTerm("native multimodal pretraining", "native-multimodal-pretraining", ["native multimodal pretraining", "原生多模态预训练"], "本课程用它指基础预训练阶段就让文本与其他模态共同参与主干学习；不同技术报告对“原生”的边界可能不同。", "看到“原生多模态”宣传语就能确定具体训练阶段、冻结策略和数据配比。"),
  defineTerm("multimodal alignment", "multimodal-alignment", ["multimodal alignment", "模态对齐", "跨模态对齐"], "通过配对数据和训练目标，让不同模态的表示能够对应同一对象、事件或任务关系。", "张量维度能够连接就表示不同模态已经在语义上对齐。"),
  defineTerm("KDA", "kda", ["KDA", "Kimi Delta Attention"], "Kimi K3 使用的门控 delta 状态更新注意力，以固定形状状态压缩历史。", "固定状态能无损替代所有全局注意力层。"),
  defineTerm("Gated MLA", "gated-mla", ["Gated MLA", "门控 MLA"], "Kimi K3 中带门控的多头潜在注意力，用于保留 token 级全局交互。", "与 KDA 的固定状态读写完全相同。"),
  defineTerm("AttnRes", "attnres", ["AttnRes", "Attention Residuals", "注意力残差"], "让当前层按学习到的权重读取多个历史层或块表示的深度连接。", "普通残差相加换了一个名称。"),
  defineTerm("Stable LatentMoE", "stable-latent-moe", ["Stable LatentMoE", "LatentMoE"], "在较窄潜空间中进行稀疏专家计算，并加入尺度稳定与负载均衡设计。", "总参数、激活参数、通信和显存都按同一比例下降。"),
  defineTerm("Quantile Balancing", "quantile-balancing", ["Quantile Balancing", "QB", "分位数均衡"], "按专家路由分数的分位位置更新选择偏置的负载均衡方法。", "一次更新就保证此后每个专家永远获得相同负载。"),
  defineTerm("MOPD", "mopd", ["MOPD", "Mixture-of-Policies Distillation"], "把多个领域与推理努力策略的行为蒸馏回一个学生模型的后训练方法。", "多个教师总能被无损合并成一个模型。")
];

export const wikiAliases = wikiTerms.flatMap((term) =>
  term.aliases.map((alias) => ({ alias, term }))
);
